### ISSUE TITLE
Missing copy_query_pool_results

### ISSUE THREAD

**Issue by kvark** [MaikKlein/ash#105]
I'm [not seeing it](https://docs.rs/ash/0.24.4/ash/?search=copy_query_pool_results) in either the function pointers or wrappers. [Spec link](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkCmdCopyQueryPoolResults.html).

**Comment by MaikKlein** [comment]
Fixed by #106

**Comment by kvark** [comment]
Yeah, not really fixed in `master` and/or published yet.

**Comment by MaikKlein** [comment]
Oh I was under the assumption that you wanted to use `ash-sys`? Is that not the case any more? I can push it to master and release a new version later today.

**Comment by kvark** [comment]
I've been working on query support and needing this function among other things specifically. Migrating to ash-sys would be an entirely different story.

**Comment by MaikKlein** [comment]
I meant, if you want to switch to `ash-sys`, then you might as well use the raw [functions pointers](https://docs.rs/ash/0.24.4/ash/vk/cmds/struct.DeviceFnV1_0.html#method.cmd_copy_query_pool_results).

**Comment by kvark** [comment]
@MaikKlein wow, I see now. Somehow, docs.rs doesn't show those if I just type `copy_query` :(

**Comment by MaikKlein** [comment]
@kvark Do you still want me to push those changes into master right now? Or would it be fast enough if we wait for the generator merge?

**Comment by kvark** [comment]
No urgency any more.

**Comment by MaikKlein** [comment]
Available in 0.25.0
