### ISSUE TITLE
Vulkan 1.1 getter functions don't work

### ISSUE THREAD

**Issue by GabrielMajeri** [MaikKlein/ash#109]
The function `get_physical_device_properties2` (and possibly others) don't work. To call this function, we have to initialize the return structure's `s_type` and `p_next`, leave the rest uninitialized, then call the function. Currently, the [code uses mem::uninitialized()](https://github.com/MaikKlein/ash/blob/3e812896ff0aa8c170feb07ba07c928bb3393c96/ash/src/instance.rs#L125) for filling the whole structure.

<hr/>

This brings up a new issue: how to support extensions in these getters? We have to initialize every extension's structure in the chain, then call the function. If I want to get, for example, `PhysicalDeviceIDProperties`, I have to initialize the first structure (`VkPhysicalDeviceProperties2`), then the `PhysicalDeviceIDProperties` structure.

It seems there is no way for us to safely wrap Vulkan getter functions. We need to allow the user to create the chain of structures themselves, and we should only take in a `&mut` to the first structure in the chain.

**Comment by Ralith** [comment]
I would expect the affected functions are all which accept pointers to structs as output arguments where the structs contain `pNext` members. "returned" here almost certainly does not mean that `pNext` will never be used.

**Comment by omni-viral** [comment]
Or if it contains `sType` member.

**Comment by MaikKlein** [comment]
Fixed by https://github.com/MaikKlein/ash/pull/133 feel free to reopen the issue if there are more special cases
