### ISSUE TITLE
Should extensions own vk::Instance / vk::Device?

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/ash#113]
Recent PR: https://github.com/MaikKlein/ash/commit/a10935eaf701845abac26dc433b43aadf29e2565

In this case `DebugUtil` owns `vk::Instance` and implicitly passes it. Should this be done to all extensions? We just need to be consistent. I don't see a reason why this shouldn't be done.

**Comment by Ralith** [comment]
Which extensions don't do this?

**Comment by GabrielMajeri** [comment]
What would be the downside to using `PhantomData` to hold a reference to the `Entry` or `Instance` we were passed in?

**Comment by MaikKlein** [comment]
>Which extensions don't do this?

I think no extension does this. I think I had a reason 2 years ago, but I can't quite remember what it was. We should just update all the existing extensions.

>What would be the downside to using PhantomData to hold a reference to the Entry or Instance we were passed in? To statically ensure the Instance we are holding hasn't been destroyed.

I definitely would want to store all those extensions in one location

```
pub struct InnerContext {
    pub entry: Entry<V1_0>,
    pub instance: Instance<V1_0>,
    pub device: Device<V1_0>,
    pub swapchain_loader: Swapchain,
    pub debug_utils_loader: DebugUtils,
..
}
```

I think lifetimes would just complicate things. You need to manually destroy them anyway, in the correct order.

**Comment by Ralith** [comment]
> I think no extension does this.

Huh? Every single extension I've checked owns a `Device` or an `Instance` as appropriate, and passes it on. Except `DebugMarker`, which is deprecated and only has a single function that takes either anyway.

> What would be the downside to using PhantomData to hold a reference to the Entry or Instance we were passed in? To statically ensure the Instance we are holding hasn't been destroyed.

Practically every Vulkan object needs manual management. The considerable decrease in ergonomics just to diverge from the library's conventions isn't justified.
