### ISSUE TITLE
Debug printing tries to convert all arrays to CStr

### ISSUE THREAD

**Issue by GabrielMajeri** [MaikKlein/ash#116]
I've tried to pretty-print a `PhysicalDeviceLimits` structure. Most fields looked OK, however some fields were shown as strings:

```
max_compute_shared_memory_size: 32768,
max_compute_work_group_count: "\xff\xff",
max_compute_work_group_invocations: 896,
```

Those fields are fixed-size arrays of `uint32_t`.
It seems the [debug formatting implementation](https://github.com/MaikKlein/ash/blob/f161e2d967bfe8192e63a8beef98c611588f4e39/generator/src/lib.rs#L1240) tries to convert all arrays (even arrays of `u32`) to `CStr`.

**Comment by MaikKlein** [comment]
Yeah that doesn't seem right, we probably should only convert static arrays of c_chars to a CStr.

**Comment by MaikKlein** [comment]
Should be fixed by https://github.com/MaikKlein/ash/pull/129
