### ISSUE TITLE
get_physical_device_features is not exposed

### ISSUE THREAD

**Issue by ethan-tqa** [MaikKlein/ash#12]
it appears that get_physical_device_features is not safely exposed anywhere, and in order to use it, caller must call `instance.fp_v1_0().get_physical_device_features(dev, &mut features);` in an unsafe block.
But this is not really right anyway, as this function is a "free" function, it does not require the instance to be passed in.

**Comment by MaikKlein** [comment]
A few functions are still missing, I'll add it after the 18th.

**Comment by MaikKlein** [comment]
Added with https://github.com/MaikKlein/ash/commit/e4e31ec9ac3ea481ea523bf1a4fbfcd77c56d523
