### ISSUE TITLE
Expose ffi macros

### ISSUE THREAD

**Issue by msiglreith** [MaikKlein/ash#125]
Exporting macros like `vk_bitflags_wrapped` , `handle_nondispatchable`, etc. would help interfacing with C middleware vulkan libraries, which provided a vulkanic API for users (e.g VMA).

Relates to the `generator` branch

**Comment by MaikKlein** [comment]
We can export them but there is also a way to construct those types from raw handles now. At least https://github.com/MaikKlein/ash/pull/122 is still missing.

**Comment by msiglreith** [comment]
Right, it's more a QoL thing :D

**Comment by msiglreith** [comment]
> We can export them but there is also a way to construct those types from raw handles now. 

To clarify, the API defines **new types** like `VmaAllocator` in a similar fashion to Vulkan native types (e.g `CommandPool`), which are also just integer handles. The proposal related to types it to allow to reuse the existing macros for defining these types also on the FFI side including all the implementations. Currently these need to be manually defined (ie. `pub struct VmaAllocator(*mut u32);`)
