### ISSUE TITLE
Generate PFN function types

### ISSUE THREAD

**Issue by msiglreith** [MaikKlein/ash#126]
VMA handles acquisition of the vulkan function pointers by exposing a struct with the necessary pointers. It would be ideal to reuse generate function pointer types of the vulkan API. Currently only a few (probably for vulkan structs) are exposed.

Relates to the `generator` branch

**Comment by MaikKlein** [comment]
Can you explain this a bit more?

I assume you want to interface with something like `VulkanMemoryAllocator`? IIRC it has a struct that you could fill with the loaded function pointers.

I think at the moment those are all private, but that should be fixed asap.

**Comment by msiglreith** [comment]
The library accesses vulkan functions using this table: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/src/vk_mem_alloc.h#L1566-L1587

Writing a Rust wrapper based on ash would require redefining the PFN types of these function types in the wrapper. Having these exposed and generated by ash would be great.
