### ISSUE TITLE
Support for VK_KHR_mir_surface should be removed

### ISSUE THREAD

**Issue by jekstrand** [MaikKlein/ash#127]
See also KhronosGroup/Vulkan-Docs#814

**Comment by MaikKlein** [comment]
Thanks for the heads up, I'll remove it later today.

**Comment by MaikKlein** [comment]
Fixed in https://github.com/MaikKlein/ash/commit/33dc8bff8f74c7362647a98f51a3911dba55e9b6 . Only the registry needs to be updated now.
