### ISSUE TITLE
AcquireNextImageKHR issue

### ISSUE THREAD

**Issue by mikedilger** [MaikKlein/ash#13]
Today I have come back to working on graphics applications (after 3 weeks away from it) and I find that I cannot get my program to work with the vulkan debug layer turned on (it works with it off).  When on, I get:

```
"vkAcquireNextImageKHR: Application has already acquired the maximum number of images (0x2)"
```

(I requested 3 images, so the 0x2 is a bit odd).  This happens right after the swapchain rebuild.

I found your post about this in January here: 
http://stackoverflow.com/questions/41502123/vkacquirenextimagekhr-application-has-already-acquired-the-maximum-number-of-im

However, I'm not using Intel / Mesa, I'm using Nvidia proprietary driver 375.39 on Ubuntu 16.04, and I've tried VulkanSDKs 1.0.37.0, 1.0.39.1, and 1.0.46.0.   The first 2 render blank (black) screens with validation on, the newest one gives the error.  (With validation off, it works fine on all of them).

If I force `vk::PresentInfoKHR.p_results` to `ptr::null_mut()` it no longer gives the error, but continues to render only a blank (black) screen.

Oddly, both ash examples work fine.  So does SaschaWillems stuff.  It's not your bug, I'm just posting here because maybe you know something that can help me out (I've spent about 5 hours today pulling out my remaining hair).

**Comment by mikedilger** [comment]
Ok I've conflated 2 issues. Luckily I have a second development machine.  Turns out the "black screen" is caused by ash, something about the commits on Apr 6 or thereafter, or the way I have updated my code to use them.  They seem so simple and I just haven't worked out why.

The newest VulkanSDKs (1.0.46) is giving me this other issue, and I'll just punt on that for a while and keep using 1.0.39.1 for now... hopefully it's their bug.

**Comment by MaikKlein** [comment]
I am still on an older sdk, I am currently pretty busy until the 18th so I can't test it. Sounds really strange that it works when the validation layers are off. 

Not much has changed just how you update the vertex buffer binding. But I am also now on AMD. I'll investigate when I find some time.

**Comment by mikedilger** [comment]
I'm pretty sure now that this "black screen" issue has nothing to do with ash.

In fact, I'm pretty sure by now that this has nothing to do with incorrect source code.   I have gotten it failing even when I roll back and depend on rolled-back dependencies.

I don't think it's a system condition causing the failures, because once a binary is compiled, it either always works or always fails.   So I'm leaning towards a rust or llvm bug.

**Comment by mikedilger** [comment]
I'm not sure of anything anymore. Now it always works with validation off and always is black with validation on (and validation always succeeds with ptr::null_mut for p_results).  This is true regardless of which SDK, which commits I choose, etc.   I can no longer get the "draws with validation layer on" state (and I didn't save any of those binaries). I'm completely flummoxed.

I'm going to shelf this project for another few weeks, work on something else.

In case your curious of the conditions:  Ubuntu 16.04, nvidia-375(.39), GTX650 (similar results on GTX 1050 Ti on my work machine)

**Comment by mikedilger** [comment]
FYI
I've dug further into this.  The "blank screen" is caused by some objects failing to render -- the clear color renders, so isn't not entirely blank.  With certain combinations of validation layers, i can actually get one pipeline to fail to render while the other renders fine (half my objects show up).  I'm heavily leaning towards the nvidia driver >=375.  I'll get my AMD R7 360 installed tomorrow to get another data point.

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1682
