### ISSUE TITLE
CreateInfos don't take slices

### ISSUE THREAD

**Issue by SiebenCorgie** [MaikKlein/ash#138]
Hi,

maybe I'm missing something but according to the Readme I thought it would be possible to use slices for the create info's and other structs. However, according to the documentation (on `generator` and `master`) the infos usually take an `*const T`. 

Example:
Creating the DeviceQueueInfo currently:
```
ash::vk::DeviceQueueCreateInfo{
            s_type: ash::vk::StructureType::DEVICE_QUEUE_CREATE_INFO,
            p_next: ptr::null(),
            flags: Default::default(),
            queue_family_index: self.queue_family_index,
            p_queue_priorities: priorities.as_slice().as_ptr(), //shouldn't .as_slice be enough?
            queue_count: priorities.len() as u32,
        }
```

Is that not implemented anymore?

**Comment by MaikKlein** [comment]
The builder pattern exposes setters with slices for you `DeviceQueueCreateInfo::builder().queue_priority(slice)`. Structs are meant to be binary compatible.

**Comment by SiebenCorgie** [comment]
So there is a builder pattern to (almost?) every vulkan struct then?

**Comment by SiebenCorgie** [comment]
I found them, thanks again!
