### ISSUE TITLE
min/max_image_count on wayland surface mixed up

### ISSUE THREAD

**Issue by SiebenCorgie** [MaikKlein/ash#144]
Hi,

I'm currently using the generator branch. When querying for max and min image count on a surface created with the wayland loader the capabilities seam to mix up the min/max image count.
Sample output: 
```
SurfaceCapabilitiesKHR { min_image_count: 4, max_image_count: 0, current_extent: Extent2D { width: 4294967295, height: 4294967295 }, min_image_extent: Extent2D { width: 1, height: 1 }, max_image_extent: Extent2D { width: 16384, height: 16384 }, max_image_array_layers: 1, supported_transforms: SurfaceTransformFlagsKHR(1), current_transform: SurfaceTransformFlagsKHR(1), supported_composite_alpha: CompositeAlphaFlagsKHR(11), supported_usage_flags: ImageUsageFlags(10111) }
```

shouldn't be min_image_count < max_image_count?

**Comment by MaikKlein** [comment]
> minImageCount is the minimum number of images the specified device supports for a swapchain created for the surface, and will be at least one.

>maxImageCount is the maximum number of images the specified device supports for a swapchain created for the surface, and will be either 0, or greater than or equal to minImageCount. A value of 0 means that there is no limit on the number of images, though there may be limits related to the total amount of memory used by presentable images.

**Comment by SiebenCorgie** [comment]
Oh my bad, thanks fort the clarification!
