### ISSUE TITLE
Support for readable depth w/ writeable stencil

### ISSUE THREAD

**Issue by gwihlidal** [MaikKlein/ash#145]
Hi,

Getting support for `VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL` and `VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL` would be very helpful - these layouts are very important for high performance 3D game engines.

```
    VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL = 1000117000,
    VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL = 1000117001,
```

Thank you!
Graham

**Comment by MaikKlein** [comment]
Are you on version 0.24? They recently got added on 0.25, see https://docs.rs/ash/0.25.0/ash/vk/struct.ImageLayout.html#impl-5 and https://docs.rs/ash/0.25.0/ash/vk/struct.ImageLayout.html#impl-4.

If you are still on 0.24. I am afraid that there were some breaking changes, see https://github.com/MaikKlein/ash/blob/master/Changelog.md#0250

**Comment by gwihlidal** [comment]
Aha! I'm actually doing the upgrade to 0.25 right now (in my https://crates.io/crates/vk-sync crate), but RLS wasn't refreshing with the 0.25 code (it was showing me 0.24).

Crisis averted! :) Thank you

**Comment by MaikKlein** [comment]
RLS uses racer under the hood and it gets confused when there are multiple impl blocks. Generally speaking everything should be there.
