### ISSUE TITLE
Update to Vulkan 1.1.85+?

### ISSUE THREAD

**Issue by gwihlidal** [MaikKlein/ash#152]
There are significant extensions added in Vulkan 1.1.85 - most notably the Turing extensions like https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_NV_mesh_shader

It would super amazing if you could update ash to support this spec version (1.1.85), as I'm trying to port over a lot of my c++ vk work to ash which includes these features.

Thank you!

**Comment by MaikKlein** [comment]
I am currently working on it, sadly this requires a few generator changes. I'll ping you when I push a new version to creates.io.

**Comment by MaikKlein** [comment]
If you need it now, you can use this branch here https://github.com/MaikKlein/ash/pull/154

**Comment by MaikKlein** [comment]
The PR above only exposes the "raw" extensions. This means you need to load those yourself. You can find examples of how it is done here https://github.com/MaikKlein/ash/tree/master/ash/src/extensions

**Comment by gwihlidal** [comment]
This is awesome; any idea when the PR will be merged in? Are you planning on adding idiomatic loaders for the extensions, or will they be raw only?

**Comment by MaikKlein** [comment]
I think I can get it merged today. I definitely would like to have all extensions exposed at a higher level but it is always a question of time. Also I don't have an nvidia gpu so I can't test it.

So for now it will be raw only.

**Comment by MaikKlein** [comment]
@gwihlidal I pushed a new version, I just saw that the MeshShader is a very small extension and I am going to implement the loader right now.

**Comment by MaikKlein** [comment]
`0.26.2` is live, https://docs.rs/ash/0.26.2/ash/extensions/struct.MeshShader.html

**Comment by gwihlidal** [comment]
Awesome, thank you very much :) I may tackle the ray tracing extension soon
