### ISSUE TITLE
Expose and use constant strings from extensions

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/ash#157]
Right now extension specify the extension name manually like

https://github.com/MaikKlein/ash/blob/master/ash/src/extensions/xcb_surface.rs#L27

It would be nice if the generator would generate those names for us.

**Comment by cormac-obrien** [comment]
It looks like this is now being handled by `vk-parse` since at least e86645d2?

**Comment by MaikKlein** [comment]
This has already been implemented, and all the extension already use it.
