### ISSUE TITLE
Should we couple or decouple function pointers from types?

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/ash#16]
Currently a device looks like this

```
#[derive(Clone)]
pub struct Device<V: FunctionPointers> {
    handle: vk::Device,
    device_fn: V::DeviceFp,
}
```

The reason behind including the device function pointers in the device itself was that they logically belong together. You are no allowed to call a device level function with a different device afaik.

Currently the function pointers are stored with out any indirection and this makes cloning rather expensive. It should definitely be placed behind a pointer, maybe an `Arc` or an unsafe pointer. Although in practice this shouldn't be a problem at all. You will most likely end up with something like this

```
struct Context{
    device: Device,
    instance: Instace,
    swapchain: Swapchain
}
```
which you also probably put behind an `Arc`.

This also raises a question if the same pattern should also be applied to other types as well. For example extensions like `Swapchain`, or handles like `PhyiscalDevice`. Or if we should decouple the function pointers from the device, like we do with the extensions. I think coupling would make it more weird to do proper versioning.

So for example instead of

```
let swapchain_loader = SwapchainLoader::new();
let swapchain = swapchain_loader.create_swapchain();
let images = swapchain_loader.get_swapchain_images_khr(swapchain);

// to 

let swapchain = Swapchain::create_swapchain(&device,...);
let images = swapchain.get_swapchain_images_khr();
```

Applying this to other types like `PhysicalDevice` would also require versioning. `PhysicalDevice<V1_0>`

We should also think about future versions of Vulkan, especially about the new multi gpu extensions, like a [DeviceGroup](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHX_device_group)

**Comment by MaikKlein** [comment]
@msiglreith I would also love to hear your input about this.

**Comment by ethan-tqa** [comment]
One comment about versioning: knowing Khronos, I doubt existing function signatures will ever change. What they will do in say version 1.1 is add new functions on top. So it would be a lot simpler to remove version type parameter, and only worry about API version while initializing.

**Comment by MaikKlein** [comment]
>One comment about versioning: knowing Khronos, I doubt existing function signatures will ever change. What they will do in say version 1.1 is add new functions on top. So it would be a lot simpler to remove version type parameter, and only worry about API version while initializing.

That is the reason they exist, they add functionality.

**Comment by ethan-tqa** [comment]
What I meant is having wrapper for all functions available in Vulkan SDK at the latest version. Users need to be carefull when calling, make sure that they only call the right functions that are supported if they initialized a Vulkan instance using older version value. So you can stick to `PhysicalDevice` instead of having to use `PhysicalDevice<V1_0>`

**Comment by MaikKlein** [comment]
>Users need to be carefull when calling, make sure that they only call the right functions that are supported if they initialized a Vulkan instance using older version value. 

That is the reason I wrote the versioning, I want static errors not runtime errors. Also the versioning makes it easy to see which version a codebase actually uses.

**Comment by MaikKlein** [comment]
Coupling

Pros:

* Safer, you can't accidentally call a function pointer with the wrong object.
* A bit more convenient

Cons: 

* Additional size for the function loaders. They maybe require an Arc or an unsafe pointer.
* More versioning

Decouple:

Pros:
* Simpler to do versioning
* Potentially more flexible
* Extensions already are decoupled.

Cons:
* Less safe
* More verbose

**Comment by ethan-tqa** [comment]
I do understand the reason to have versioning, but it seems to introduce a high amount of complexity and "friction", as Jon Blow call it.

**Comment by msiglreith** [comment]
I would prefer to keep it the current way. Coupling would induce Arcs when it's not really necessary and imo we often only safe 1-2 lines of code with coupling but that's only a low percentage of the whole vulkan code.

Overall the advantages/disadvantages for both approaches are quite small, so both should work fine.

**Comment by MaikKlein** [comment]
>I would prefer to keep it the current way. Coupling would induce Arcs when it's not really necessary and imo we often only safe 1-2 lines of code with coupling but that's only a low percentage of the whole vulkan code.
Overall the advantages/disadvantages for both approaches are quite small, so both should work fine.

I am thinking the same thing right now. I don't think any changes are necessary right now. I'll wait until I can play around with `DeviceGroups` to see if there are any problems with the current approach.
