### ISSUE TITLE
Should extensions include the vendor tag?

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/ash#163]
`Swapchain` -> `KhrSwapchain`, `MeshShader` -> `NvMeshShader`...

I think this would be more consistent in the long run.

We then should also remove the extension tag from the functions names like `acquire_next_image_khr`-> `acquire_next_image` because it is already named in the extension.

I also propose to change `Extension::new` to `Extension::load`, I think `new` is a bit misnamed.

Thoughts?

**Comment by Ralith** [comment]
Perhaps per-vendor modules?

**Comment by MaikKlein** [comment]
That would also be an option. I like that even better.

**Comment by gwihlidal** [comment]
+1 for per-vendor

**Comment by MaikKlein** [comment]
Fixed in https://github.com/MaikKlein/ash/pull/167
