### ISSUE TITLE
Surface::get_physical_device_surface_support doesn't return VkResult

### ISSUE THREAD

**Issue by dylanede** [MaikKlein/ash#185]
The Vulkan spec specifies that `vkGetPhysicalDeviceSurfaceSupportKHR` returns a result that can be an error. `Surface::get_physical_device_surface_support` however currently returns only a `Bool32`, and the implementation of the function discards the result from `vkGetPhysicalDeviceSurfaceSupportKHR`. This doesn't seem to be correct. It should probably return `VkResult<Bool32>` instead.

**Comment by Ralith** [comment]
Or even `VkResult<bool>`, perhaps? Since we're writing a wrapper anyway.

**Comment by dylanede** [comment]
Yeah that would make more sense.
