### ISSUE TITLE
const fn for BitFlags (where it's currently possible)

### ISSUE THREAD

**Issue by gabdube** [MaikKlein/ash#187]
In my vulkan application, I use a constant struct to define my engine base configuration. The thing is, it is not current possible to combine the ash bitflags in constants or static expressions. For example, right now this code do not work:

```rust 
const REQUIRED_QUEUE_FLAGS = vk::QueueFlags::COMPUTE | vk::QueueFlags::GRAPHICS;
```

That's because (as far as I know) `BitOr` cannot use `const fn`. I guess that's a Rust limitation. So I tried doing this instead:

```rust
const REQUIRED_QUEUE_FLAGS =  vk::QueueFlags::from_raw(0b1 | 0b10),  // GRAPHICS / COMPUTE 
```

Which didn't work either because the `vk_bitflags_wrapped` do not declare `from_raw` as a const fn. So I cloned the repo and declared `empty`, `all`, `from_raw` and `as_raw` as `const fn` to see if anything would explode. So far everything works fine.

Would it be fine to merge my changes in the main branch?

**Comment by MaikKlein** [comment]
That is a bit unfortunate. These accessors should probably be const. Keep in mind that `vk.rs` is generated. I just realized that there are no docs about how to use the generator, I'll add them today.

**Comment by MaikKlein** [comment]
You would want to change the macro here https://github.com/MaikKlein/ash/blob/master/generator/src/lib.rs#L200

And regenerate the vk.rs with

`cargo run --release; rustup run stable rustfmt ../ash/src/vk.rs`

**Comment by gabdube** [comment]
Alright. Thanks. Should I close this issue?

**Comment by MaikKlein** [comment]
Leave it open, I will close it when it is merged.
