### ISSUE TITLE
get_physical_device_X_presentation_support_khr not exposed

### ISSUE THREAD

**Issue by jminer** [MaikKlein/ash#197]
I wanted to call `get_physical_device_win32_presentation_support_khr` today, but it doesn't seem to have a higher-level wrapper available. I see that `Win32Surface` creates a `KhrWin32SurfaceFn` and wraps its `create_win32_surface_khr`, but that's it. Similarly, the XCB, Xlib, and Wayland presentation support functions don't have wrappers.

**Comment by MaikKlein** [comment]
Probably just an oversight because you can also check for crossplatform presentation support with `vkGetPhysicalDeviceSurfaceSupportKHR`. We probably should still expose those functions.
