### ISSUE TITLE
Crash on get_physical_device_surface_capabilities() on wayland surface.

### ISSUE THREAD

**Issue by SiebenCorgie** [MaikKlein/ash#198]
Hi,

I currently try to get my ash based application to create a surface on wayland via winit.
The creation process succeeds, but every time I try to access the surface capabilities via
`surface_loader.get_physical_device_surface_capabilities(pdevice, surface)` the application crashes with `Result(-3)` which is "Initialization of a object has failed".

So I tried to find the problem by enhancing the example's lib.rs like this:

SurfaceLoading:
```
#[cfg(all(unix, not(target_os = "android"), not(target_os = "macos")))]
unsafe fn create_surface<E: EntryV1_0, I: InstanceV1_0>(
    entry: &E,
    instance: &I,
    window: &winit::Window,
    events_loop: &EventsLoop
) -> Result<vk::SurfaceKHR, vk::Result> {
    use winit::os::unix::WindowExt;
    use winit::os::unix::EventsLoopExt;
    
    //Check if we are on wayland, if not, use x11
    if events_loop.is_wayland(){
        use ash::extensions::khr::WaylandSurface;

        let way_display = window.get_wayland_display().expect("failed to get wayland display!");
        let way_surface = window.get_wayland_surface().expect("fauked to get wayland surface");

        let way_create_info = ash::vk::WaylandSurfaceCreateInfoKHR::builder()
            .display(way_display)
            .surface(way_surface);
        //Create the surface loader
        let way_surface_loader = WaylandSurface::new(
            entry,
            instance
        );
        way_surface_loader.create_wayland_surface(&way_create_info, None)
    }else{
        let x11_display = window.get_xlib_display().unwrap();
        let x11_window = window.get_xlib_window().unwrap();
        let x11_create_info = vk::XlibSurfaceCreateInfoKHR::builder()
            .window(x11_window)
            .dpy(x11_display as *mut vk::Display);

        let xlib_surface_loader = XlibSurface::new(entry, instance);
        xlib_surface_loader.create_xlib_surface(&x11_create_info, None)
    }   
}
```
I also added the WaylandSurface extension like that:
```
#[cfg(all(unix, not(target_os = "android"), not(target_os = "macos")))]
fn extension_names() -> Vec<*const i8> {
    vec![
        Surface::name().as_ptr(),
        XlibSurface::name().as_ptr(),
        WaylandSurface::name().as_ptr(),
        DebugReport::name().as_ptr(),
    ]
}
```
However, the lib.rs also crashes when trying to get the capabilities with the same error.

My question now: am I missing something in the creation process?
I tested this on gnome-wayland and sway, both with intel-anv and radeon-mesa drivers.

**Comment by MaikKlein** [comment]
I am not sure what is going on. `-3` is also not a legal error code. Have to tried to run https://github.com/SaschaWillems/Vulkan? Afaik they also have wayland support.

I can't see an obvious mistake in your code.

**Comment by SiebenCorgie** [comment]
I compiled SaschaWillems's examples two time, once with USE_WAYLAND_WSI enabled and once with it disabled.

When started on gnome+wayland the the examples work when USE_WAYLAND_WSI is disabled, but crash with the following error when enabled:
```
Fatal : VkResult is "ERROR_INITIALIZATION_FAILED" in /home/user/Code/CPP/git/Vulkan/base/VulkanSwapChain.hpp at line 287
bloom: /home/user/Code/CPP/git/Vulkan/base/VulkanSwapChain.hpp:287: void VulkanSwapChain::create(uint32_t*, uint32_t*, bool): Assertion `res == VK_SUCCESS' failed.
[1]    4827 abort (core dumped)  ./bloom

```

I guess I'm using Wayland_WSI when creating a wayland surface so it could be the same bug.

**Comment by SiebenCorgie** [comment]
I wrote an Issue at the example repo. Let's see if this is somehow related. Maybe I'm missing just some package or something.

https://github.com/SaschaWillems/Vulkan/issues/567

**Comment by SiebenCorgie** [comment]
So I found the problem. It seems to be an AMD-Pro driver issue on linux. It works with the open-source RADV driver. 
The problem on SashaWillem's examples were actually caused by some wrong configuration of the CMAKE scripts.
