### ISSUE TITLE
Should I use Ash?

### ISSUE THREAD

**Issue by knappador** [MaikKlein/ash#200]
I began with Vulkano a while back when it was one of the few Vulkan libraries. 

My project is really struggling to move forward on basic synchronization issues and I'm not super happy with the level of abstraction and how it's affecting the project health and trajectory.

https://github.com/e-nguyen/e-nguyen

Most importantly, I am looking for a good community where PR's and design etc are interactive.  I need to place future E-Nguyen users in a good home.  **If this issue gets 37k upvotes, I'll begin porting.**

**Comment by Ralith** [comment]
Ash is, more or less, raw Vulkan. It's up to you to determine whether a low-level binding is appropriate for your use case.

**Comment by knappador** [comment]
This reply speed says it all.  :+1: :+1: :+1:
