### ISSUE TITLE
docs.rs Search Broken

### ISSUE THREAD

**Issue by knappador** [MaikKlein/ash#203]
I believe this is totally an external issue.

https://docs.rs/ash/0.29.0/ash/?search=Instance

One of the scripts is refused by browsers for loading over http.  This throws an error and we get no API search.

Other crates' documentation is working.

**Comment by knappador** [comment]
> 23:23 < Moongoodgirl{K}> that's suspicious
23:24 < elomatreb> Yeah it's a bug with apparently all newly built docs.rs pages since a 
                   few days, you might try an older version

**Comment by MaikKlein** [comment]
Yeah I saw a couple of other crates with this problem too. Worst case we need to release a new patch version.

**Comment by knappador** [comment]
Should get...
Fixed in rust-lang/docs.rs#329
