### ISSUE TITLE
VulkanSDK 1.1.92.1 breaks examples

### ISSUE THREAD

**Issue by NLincoln** [MaikKlein/ash#205]
# The issue

Running the examples with a vulkansdk >= 1.1.92.1 on macOS renders a black screen. Nothing on stdout / stderr. I have tested with both debug mode and release mode configuration.

For completeness, I have also checked every release after 1.1.92.1. They render a black screen.

# How to reproduce:

- `git clone` this repo
- download vulkansdk 1.1.92.1 from [this link](https://vulkan.lunarg.com/sdk/home#mac)
- set up the env vars using the README instructions
- run the examples, black screen

You can verify that everything should be working by downloading version 1.1.85.0, resetting the env vars to use that, and the examples should work.

# My environment

- latest master branch of this repo
- macOS 10.12
- rustc 1.34 stable

**Comment by NLincoln** [comment]
Note that it's unlikely this is a duplicate of #149, since the latest vulkansdk at that point was 1.1.85.0, which I've confirmed to work.

**Comment by NLincoln** [comment]
I should also note that the sdk-provided example (vkcube) _does work_ in the latest release of the vulkansdk for me, so it appears to be a problem related to ash.

**Comment by MaikKlein** [comment]
Thanks for the report. Sadly I don't have immediate access to a mac atm. I'll try to reproduce it as soon as I can.

**Comment by unknownue** [comment]
This problem reproduce on my macbook too. 
It does take me some time to experiment what is the problem.
And I found that after changing all the requested memory flags from `vk::MemoryPropertyFlags::HOST_VISIBLE` to `vk::MemoryPropertyFlags::HOST_VISIBLE | vk::MemoryPropertyFlags::HOST_COHERENT`, the triangle finally appeared on screen.

Following is what the `vulkaninfo` command prints on my macbook with SDK version 1.1.101.

	VkPhysicalDeviceMemoryProperties:
	=================================
	memoryHeapCount       = 1
	memoryHeaps[0] :
		size          = 4294967296 (0x100000000) (4.00 GiB)
		flags:
			VK_MEMORY_HEAP_DEVICE_LOCAL_BIT
	memoryTypeCount       = 3
	memoryTypes[0] :
		heapIndex     = 0
		propertyFlags = 0x1:
			VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT
	memoryTypes[1] :
		heapIndex     = 0
		propertyFlags = 0xb:
			VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT
			VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT
			VK_MEMORY_PROPERTY_HOST_CACHED_BIT
	memoryTypes[2] :
		heapIndex     = 0
		propertyFlags = 0xf:
			VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT
			VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT
			VK_MEMORY_PROPERTY_HOST_COHERENT_BIT
			VK_MEMORY_PROPERTY_HOST_CACHED_BIT

It seems that the example codes choose a non-coherent memory and forget to flush the memory.

**Comment by unknownue** [comment]
To fix the problem, the following solutions both work on my machine:

- Change all the request memory flags to `vk::MemoryPropertyFlags::HOST_VISIBLE | vk::MemoryPropertyFlags::HOST_COHERENT`.
- Call `device::flush_mapped_memory_ranges()` to confirm the memory data transfer.

May be I can open new PR to fix this problem. Which solution is preferred? @MaikKlein

**Comment by Ralith** [comment]
Thank you for that great investigation! I'd favor an explicit flush, personally.

**Comment by MaikKlein** [comment]
In this specific case I think the device local + host visible would be the best memory type for an upload. But lets just got with host visible + host coherent for everything in the samples, then we don't need to worry about flushes. 

Most samples seems to prefer coherent memory for this. https://github.com/SaschaWillems/Vulkan/blob/master/examples/triangle/triangle.cpp#L424

https://github.com/LunarG/VulkanSamples/blob/master/API-Samples/13-init_vertex_buffer/13-init_vertex_buffer.cpp#L90

**Comment by MaikKlein** [comment]
fixed by #212
