### ISSUE TITLE
MoltenVK deprecation warning - add vkCreateMetalSurfaceEXT

### ISSUE THREAD

**Issue by repi** [MaikKlein/ash#221]
When running Ash on Mac through MoltenVK we get this warning: 

```
[mvk-info] vkCreateMacOSSurfaceMVK(): This function is obsolete. Consider using the vkCreateMetalSurfaceEXT() function from the VK_EXT_metal_surface extension instead
```

Talked to @MaikKlein and think `vkCreateMetalSurfaceEXT` is not exposed yet in Ash though so would have to be added to solve this properly

**Comment by MaikKlein** [comment]
Updated the generator in #222. Now we just need to expose the extension.
