### ISSUE TITLE
get_physical_device_memory_properties crash on Windows 10 in release mode

### ISSUE THREAD

**Issue by maeln** [MaikKlein/ash#225]
Hello!

# Summary 
Calling the function [get_physical_device_memory_properties](https://docs.rs/ash/0.29.0/ash/version/trait.InstanceV1_0.html#method.get_physical_device_memory_properties) on Windows 10 with cargo set to compile in release mode ( `cargo run --release` ) crash with the following error:

```
error: process didn't exit successfully: `target\release\wyzoid.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

# Description
I work on a small project, that use ash, that simply:
- load data onto a buffer
- execute a compute shader on the buffer
- return the value 

[(source code)](https://github.com/maeln/wyzoid)

I program it mostly on my 2015 Macbook pro (so Mac OS X & Intel CPU & Integrated GPU). The project compile and execute fine *in any mode (debug & release)* on it.

Compiling and running the same project on a Windows 10 machine (with Intel CPU and NVidia GTX1070 GPU) works fine *in debug mode* but will crash in release mode *with any optimisation level*, with the following error:
```
error: process didn't exit successfully: `target\release\wyzoid.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

Using 
```
[profile.release]
opt-level = 0
debug = true
```

I manage to track down the error to the `get_physical_device_memory_properties` (vk.rs:966) line.
Which is extra weird since, at this point, every data seem to be properly initialized (`physical_device` as the right value, `memory_prop` as been properly initialized and has the right value).

# Step to reproduce
1. Clone [this project](https://github.com/maeln/wyzoid)
2. Run `cargo run` : Should work fine
3. Run `cargo run --release` : Should crash

# End note
This one looks like a fun one. Honestly, I doubt that it comes from `ash`, since every pointer seems to be initialized properly (vulkan function pointer too). I will investigate the drivers and also try to reproduce the issue in CPP if I can.

**Comment by maeln** [comment]
Using https://gist.github.com/sheredom/523f02bbad2ae397d7ed255f3f3b5a7f (which is what my code is mostly based on), I was unable to reproduce the bug with in C, with Visual Studio 2019, in Debug and Release, on the same machine.

**Comment by MaikKlein** [comment]
Thanks I only looked at your issue very briefly but it seems you are dropping `Entry`, which unloads the dll and then crashes. I'll have a closer look at it tonight.

See https://github.com/MaikKlein/ash#function-pointer-loading

**Comment by aloucks** [comment]
I suspect @MaikKlein is right about dropping the `Entry`.

Querying the memory properties immediately after selecting the physical device succeeds (and `Entry` is still in scope):

```rust
physical = phy_count[phy_id];

unsafe {
    let props = instance.get_physical_device_memory_properties(physical);
    dbg!(props);
}
```

**Comment by maeln** [comment]
Yes, I put the entry in my struct that serves as a state and now it doesn't crash. Its weird that it only crash on w10 but I guess there is some weird compiler optimization quirck.
