### ISSUE TITLE
Raw pointers not exposed in extension loading structs

### ISSUE THREAD

**Issue by Didgy74** [MaikKlein/ash#226]
The raw function pointers are not exposed for extension-loader structs, among them are `ash::extensions::khr::Surface` and `ash::extensions::khr::Swapchain`.

I see that these structs contain underlying structs for the raw function pointers (i.e `vk::KhrSurfaceFn`), making the structs public and providing getters to non-mut references for them can work as a quick fix.

**Comment by Ralith** [comment]
I believe this was fixed by #234.
