### ISSUE TITLE
Rename parameter name in ash::extensions::khr::Surface

### ISSUE THREAD

**Issue by Didgy74** [MaikKlein/ash#228]
The function [get_physical_device_surface_support](https://docs.rs/ash/0.29.0/ash/extensions/khr/struct.Surface.html#method.get_physical_device_surface_support) has the second parameter named "queue_index". The original spec has this parameter named as "queueFamilyIndex", as seen [here](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkGetPhysicalDeviceSurfaceSupportKHR.html). This can create confusion since the distinction between queue and queue-family is very important.

I propose we rename this parameter name to "queue_familiy_index".

**Comment by Ralith** [comment]
I would approve a PR that did this.
