### ISSUE TITLE
Physical device features chain

### ISSUE THREAD

**Issue by msiglreith** [MaikKlein/ash#229]
`vkPhysicalDeviceFeatures2Builder` has no `push_next` method.

`vkPhysicalDeviceFeatures2` has been introduced as the original `vkPhysicalDeviceFeatures` containes no `pNext` field. Vulkan allows new physical device feature extensions to be added in the next chain of either `vkPhysicalDeviceFeatures2` or `vkDeviceCreateInfo`. As `vkPhysicalDeviceFeatures2` is effectively also in the `vkDeviceCreateInfo` chain this results in that it will be not marked as root struct and therefore no `push_next` is generated.

It's per se not a blocker just inconvenient in my opinion. Perhaps, `vkPhysicalDeviceFeatures2` could be manually whitelisted somehow?

**Comment by MaikKlein** [comment]
Sorry not for responding sooner, I'll look into it now.

**Comment by MaikKlein** [comment]
Yes that should be possible, thanks for the report.

**Comment by zakarumych** [comment]
It's still not there :(

**Comment by filnet** [comment]
I came up with a hopefully proper fix:
* implement a `push_next` functions for all structures that declare a `p_next` field (used to do it only for "root" structures)
* honor all extends (was honoring only "root" extends)
* removed `root_struct_names` function as it was not used anymore (the notion of root structure is not well defined in Vulkan)
