### ISSUE TITLE
Device - ErrorExtensionNotPresent

### ISSUE THREAD

**Issue by hodasemi** [MaikKlein/ash#23]
Hi,

I am just starting to use your crate, I just encountered an error. When creating a Device with the "VK_EXT_debug_report" extension, I get the ErrorExtensionNotPresent result.
Not sure why it doesnt work. I have a running C++ programm on the same machine with this extension.

**Comment by MaikKlein** [comment]
That is probably because it is an instance extension, not a device extension. https://vulkan.lunarg.com/doc/view/1.0.26.0/linux/vkspec.chunked/apcs04.html

Did you encounter this error when running the examples?

**Comment by MaikKlein** [comment]
See https://github.com/MaikKlein/ash/blob/master/examples/src/lib.rs#L124 and https://github.com/MaikKlein/ash/blob/master/examples/src/lib.rs#L269

**Comment by hodasemi** [comment]
Oh yea, I messed it up. I wanted to use VK_EXT_debug_marker instead. Always these irritating namings.
Sorry for inconvenience.

**Comment by MaikKlein** [comment]
No problem, but I don't think that I have wrapped this extension yet. I'll do it as soon as I can.
