### ISSUE TITLE
Release 9838cf9.

### ISSUE THREAD

**Issue by cheako** [MaikKlein/ash#237]
I uploaded "Avoid allocation for spirv shaders" under the name ash-tray and have been using it for the past month without issue.

I see recently some commits to add new features and was wondering if, before you get knee deep into debugging these new features, you wouldn't run cargo publish on this older/usable/stable version?

Thanks.

**Comment by cheako** [comment]
You might want to take a look at ash-tray-rs on gitlab there is a script that does some housecleaning on ash you might borrow from.

**Comment by cheako** [comment]
I spoke too soon.  I just ran into an issue with vk::VertexInputAttributeDescriptionBuilder and others like it that don't contain ptrs.  I would like it to be Clone and it doesn't need the lifetime generic.

**Comment by Ralith** [comment]
It looks like that commit only touches example code?

**Comment by cheako** [comment]
I'm talking about that commit and everything preceding it.  I updated my script with a small patch to clean up VertexInputAttributeDescriptionBuilder to allow me to manage it the way I needed.

https://gitlab.com/cheako/ash-tray-rs/blob/139ab4c00f721d8dd0b885d2d66b60002e37bb62/rebase-ash.sh#L39

Though this change shouldn't be made to the stable 9838cf9.  Because of this missing feature, this publishing doesn't effect me anymore.  I would still make a release, just to reset the age of the current release.

**Comment by Ralith** [comment]
Okay.
