### ISSUE TITLE
Make extensions names constant

### ISSUE THREAD

**Issue by nifker** [MaikKlein/ash#238]
The 'name' functions from e.g. "ash::extensions::khr::Surface" and other extensions should be const.

**Comment by Ralith** [comment]
This is not currently possible, as `from_bytes_with_nul_unchecked` is not const in stable rust.

**Comment by Friz64** [comment]
> This is not currently possible, as `CStr::from_bytes_with_nul_unchecked` is not const in stable rust.

It is now.

**Comment by MaikKlein** [comment]
Oh nice, I've totally missed that. I'll fix it after I am done refactoring the generator.

**Comment by Friz64** [comment]
Additionally, this issue is pretty much the same as https://github.com/MaikKlein/ash/issues/79.

**Comment by MaikKlein** [comment]
Yeah closing this in favor of #79

**Comment by Ralith** [comment]
> It is now.

It is not. The nightly feature in question is `const_cstr_unchecked`. rustdoc displays the `const` qualifier erroneously.

**Comment by Friz64** [comment]
Oh wow, i didn't know that rustdoc is not to trust sometimes.

**Comment by Friz64** [comment]
I guess we can still make it happen by copying the implementation of `from_bytes_with_nul_unchecked`.

```rust
pub const unsafe fn from_bytes_with_nul_unchecked(bytes: &[u8]) -> &CStr {
    &*(bytes as *const [u8] as *const CStr)
}
```

**Comment by Ralith** [comment]
If it were that simple it would already be stable:
> error[E0658]: dereferencing raw pointers in constant functions is unstable

**Comment by Friz64** [comment]
Oh, i thought it was some weird thing where a perfectly working function is still not stable.
