### ISSUE TITLE
Incomplete return value in DeviceV1_0::get_fence_status 

### ISSUE THREAD

**Issue by maeln** [MaikKlein/ash#242]
Hello,

It seem to me that the current return value in [DeviceV1_0::get_fence_status](https://docs.rs/ash/0.29.0/ash/version/trait.DeviceV1_0.html#method.get_fence_status) is incomplete compared to its "raw" equivalent [DeviceFnV1_0](https://docs.rs/ash/0.29.0/ash/vk/struct.DeviceFnV1_0.html#method.get_fence_status).

The first one return `VkResult<()>` whereas the "raw" one return `Result`. We lose the information of the result value in the process which is not desirable due to the nature of the spec ( [fence](https://vulkan.lunarg.com/doc/view/1.1.121.2/windows/chunked_spec/chap6.html#synchronization-fences) ), we usually want to do something like this:

```
let status = unsafe { 
    self.state.device.get_fence_status(self.fence).expect("[ERR] Could not fetch fence status") 
};

match status {
    vk::Result::SUCCESS => FenceStates::SIGNALED,
    vk::Result::NOT_READY => FenceStates::UNSIGNALED,
    vk::Result::ERROR_DEVICE_LOST => FenceStates::LOST,
     _ => FenceStates::UNKNOWN,
}
```

But currently, it is not possible. But replacing it with:

```
let status = unsafe { 
    self.state.device.fp_v1_0().get_fence_status(self.state.device.handle(), self.fence)
};
```

Does allow to get the result wanted.

Faithfully yours,

**Comment by Ralith** [comment]
`VkResult<bool>` might be appropriate here. Generally you'll be fine just checking `is_ok()`, though; if the device is lost you'll find out shortly regardless.

**Comment by maeln** [comment]
I think discriminating between your queue is still busy or all hell broke lose is still important :) . `VkResult<bool>` could fit the bill (provided that it is properly documented what are the `Result` equivalent).

**Comment by msiglreith** [comment]
Related: https://github.com/MaikKlein/ash/issues/41

`https://docs.rs/ash/0.29.0/ash/version/trait.DeviceV1_0.html#method.get_event_status` is a similar candidate where `VkResult<bool>` was used for indicating set/reset.
