### ISSUE TITLE
Running with wine on linux fails with "Unable to load get_instance_proc_addr"

### ISSUE THREAD

**Issue by stevebob** [MaikKlein/ash#251]
To reproduce, build the triangle example for windows (msvc/gnu), and run the binary with wine. I set up an appveyor job to build the triangle example: https://ci.appveyor.com/project/stevebob/ash/build/job/tac8goyl6t8aghm9/artifacts

Downloading, extracting, and running that with wine gives the output:
```
$ wine triangle.exe
002c:fixme:msg:IsGUIThread 1: stub
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 1.
thread 'main' panicked at 'Unable to load get_instance_proc_addr', ash\src\vk.rs:282:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

My version of wine is 4.20.
I've tested that I can run other vulkan programs with wine, namely https://github.com/skeeto/vulkan-test

**Comment by Ralith** [comment]
That's odd; it looks like it found a vulkan-1.dll, but that .dll didn't have the expected symbols. Do you know where the dll it found is from?

**Comment by stevebob** [comment]
I did some digging today. Haven't solved it yet, but here's what I found out:
The output of
```
WINEDEBUG=+loaddll wine triangle.exe
```
...includes
```
002b:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\vulkan-1.dll" at 0x7f4e59100000: builtin
002b:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\winevulkan.dll" at 0x7f4e590b0000: builtin
```
According to `winedump`, both these files (inside my ~/.wine/drive_c dir) are "Wine fake DLLs". These files contain no code, and by some magic that I don't understand yet, when a windows program would link with one of these files, it actually links with a correspondingly-named file in /usr/lib/wine.
My wine installation came with:
```
/usr/lib/wine/vulkan-1.dll.so
/usr/lib/wine/winevulkan.dll.so
```
The strace of the triangle example includes these files:
```
$ strace wine triangle.exe 2>&1 | grep 'vulkan.*\.dll.so'
openat(AT_FDCWD, "/usr/bin/../lib/wine/vulkan-1.dll.so", O_RDONLY) = 18
openat(AT_FDCWD, "/usr/bin/../lib/wine/vulkan-1.dll.so", O_RDONLY|O_CLOEXEC) = 18
openat(AT_FDCWD, "/usr/bin/../lib/wine/winevulkan.dll.so", O_RDONLY) = 18
openat(AT_FDCWD, "/usr/bin/../lib/wine/winevulkan.dll.so", O_RDONLY|O_CLOEXEC) = 18
```
I listed the symbols in both these files, and found this:
```
 $ nm -D /usr/lib/wine/winevulkan.dll.so | grep InstanceProcAddr
0000000000027d10 T native_vkGetInstanceProcAddrWINE
000000000001c760 T wine_vkGetInstanceProcAddr
00000000000267a0 T wine_vk_icdGetInstanceProcAddr
```
The vulkan test app (which can successfully call `vkGetInstanceProcAddr`) also links against the above files. I'm curious whether this problem is specific to vulkan, or affects dynamically-linked windows rust binaries in general.

**Comment by MaikKlein** [comment]
If I look at `vulkan-1.dll.so`, it has no vulkan smybols at all.
```
nm -D /usr/lib/wine/vulkan-1.dll.so
                 w __cxa_finalize
0000000000019f00 B _end
                 w __gmon_start__
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 U __stack_chk_fail
                 U __wine_dll_register
                 U __wine_main_argc
                 U __wine_main_argv
```
It is unclear to me what the purpose of this dll is

**Comment by Ralith** [comment]
It sounds like wine is doing some sort of magic here that we're inadvertently bypassing, which is interesting because we shouldn't be doing anything particularly weird. The one difference I can easily imagine between ash and some other simple vulkan code might be that ash takes care to dynamically load all function pointers it can, rather than letting the Vulkan loader dispatch them through its internal lookup table. 

> I am not very familiar with dlsym, maybe this is a case where we need RTLD_NEXT?

I don't imagine those exact APIs are involved on the windows codepath.

**Comment by MaikKlein** [comment]
> I don't imagine those exact APIs are involved on the windows codepath.

Right I was looking at the wrong code path.

It seems to call the same things under the hood 
https://github.com/tomaka/shared_library/blob/master/src/dynamic_library.rs#L387-L389

The only difference that I can spot is that `shared_library` also does some error checking https://github.com/tomaka/shared_library/blob/master/src/dynamic_library.rs#L370-L385

**Comment by Friz64** [comment]
So i did a little test where i used the `winapi` crate to do basically the exact same process (`LoadLibraryA`/`LoadLibraryW` and then `GetProcAddress`) and did not run into any issues with wine. For testing purposes i called `EntryV1_0::enumerate_instance_extension_properties` and got approriate output. Here's the testing code:

Cargo.toml
```
[package]
name = "vulkan-windows-loader"
version = "0.1.0"
authors = ["Friz64 <friz64mc@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3", features = ["libloaderapi"] }
ash = "0.29"
```

src/main.rs
```rustuse ash::{version::EntryV1_0, EntryCustom};
use std::{ffi::OsStr, os::windows::ffi::OsStrExt};
use winapi::um::libloaderapi::{GetProcAddress, LoadLibraryW};

fn main() {
    let entry = EntryCustom::new_custom(
        || {
            let dll_name = OsStr::new("vulkan-1.dll");
            let dll_name_encoded: Vec<_> =
                dll_name.encode_wide().chain(Some(0).into_iter()).collect();
            let vulkan_library = unsafe { LoadLibraryW(dll_name_encoded.as_ptr()) };

            if vulkan_library.is_null() {
                Err(ash::LoadingError::LibraryLoadError(
                    "Failed to load vulkan library".into(),
                ))
            } else {
                Ok(vulkan_library)
            }
        },
        |vulkan_library, function_name| unsafe {
            GetProcAddress(*vulkan_library, function_name.as_ptr()) as _
        },
    )
    .unwrap();

    dbg!(entry.enumerate_instance_extension_properties());
}
```
