### ISSUE TITLE
EntryV1_1

### ISSUE THREAD

**Issue by mikedilger** [MaikKlein/ash#254]
Is EntryV1_1 being held back for a reason?  I.e.: this code is missing:

````rust
impl<L> EntryV1_1 for EntryCustom<L> {
    fn fp_v1_1(&self) -> &vk::EntryFnV1_1 {
        &self.entry_fn_1_1
    }
}
````
Is there some other way to enter vulkan 1.1?  All the examples use 1_0 so they aren't giving me any clues.

**Comment by Ralith** [comment]
There's only one `Instance` struct and it supports all the versions; you'll just need to check what version you actually get, e.g. by calling https://docs.rs/ash/0.29.0/ash/struct.EntryCustom.html#method.try_enumerate_instance_version

**Comment by mikedilger** [comment]
Thanks for that advice, my code is working okay.   But is `EntryV1_1` pointless then?  Nothing implements it.  Kinda confusing.

**Comment by Friz64** [comment]
Hmm, this seems to be an oversight. You are correct, it should probably be implemented. `EntryV1_1::enumerate_instance_version` just seems to be sitting there not being usable.

**Comment by MaikKlein** [comment]
I guess there is no harm in implementing it for consistency but https://docs.rs/ash/0.29.0/ash/struct.EntryCustom.html#method.try_enumerate_instance_version is really what everyone should use as it works with vulkan 1.0 as well. The docs should probably point to that.

**Comment by aloucks** [comment]
> Thanks for that advice, my code is working okay. But is EntryV1_1 pointless then? Nothing implements it.

It doesn't serve any purpose currently as far as I can tell and it would be highly unsafe to use anyway. As I stated on the PR request, the function pointers wouldn't exist in a 1.0 instance and it would segfault. The Entry API probably needs to be refactored (the traits probably don't need to exist). Adding implementations just for consistently will likely make things more confusing instead of less.

https://github.com/MaikKlein/ash/pull/265/files#discussion_r368659235

**Comment by MaikKlein** [comment]
> As I stated on the PR request, the function pointers wouldn't exist in a 1.0 instance and it would segfault. 

It defaults to a function that always panics, so no segfault. `try_enumerate_instance_version` is still the way to go, maybe we expose `enumerate_instance_version` but mark it as deprecated.

**Comment by Friz64** [comment]
> ...maybe we expose `enumerate_instance_version` but mark it as deprecated.

That's the idea i had in https://github.com/MaikKlein/ash/pull/265#discussion_r368676484, it sounds like a good solution, but i don't know what @aloucks thinks of it.
