### ISSUE TITLE
vkGetPhysicalDeviceFeatures2 is not exposed

### ISSUE THREAD

**Issue by hrydgard** [MaikKlein/ash#258]
`instance.get_physical_device_features` exists, but I want to check for extension features - for which you need `vkGetPhysicalDeviceFeatures2`. That one does not seem to be exposed, as there's no get_physical_device_features2`?

I assume it's somehow related to https://github.com/MaikKlein/ash/issues/12 since it's also a "free function" that neither takes an instance nor a device (though I think as seen from the loader it's "instance-scoped", sort of).

**Comment by MaikKlein** [comment]
It is exposed as a function pointer https://docs.rs/ash/0.29.0/ash/vk/struct.InstanceFnV1_1.html#method.get_physical_device_features2, but it is currently missing from the high level wrapper.

**Comment by MaikKlein** [comment]
Just to note it is correctly marked as an instance level function, as this is where the function pointer comes from with https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkGetInstanceProcAddr.html

Had to look it up myself again, I probably should document that somewhere.
