### ISSUE TITLE
The trait `std::cmp::Eq` is not implemented for `ash::vk::Extent2D`

### ISSUE THREAD

**Issue by unknownue** [MaikKlein/ash#259]
The trait `std::cmp::Eq` is not implemented for `ash::vk::Extent2D`, but is implemented for `ash::vk::Extent3D` in version 0.29.0
Due to this problem, we can not use `ash::vk::Extent2D` as the key value of `HashMap` or `HashSet`.

**Comment by aloucks** [comment]
I think this is fixed on master: #248

**Comment by MaikKlein** [comment]
@aloucks Right good catch, I should prepare some changelogs for a new version.
