### ISSUE TITLE
Add NONE option to flags types

### ISSUE THREAD

**Issue by IGJoshua** [MaikKlein/ash#274]
Currently there doesn't appear to be a way to store an empty flags value, because the constructor for the type is private and there is no NONE option.

This seems like it should be a simple operation, and sure, right now it can be done with Option, but that seems a little weird given flags fields can often be empty.

**Comment by Friz64** [comment]
What about the `empty` function?

**Comment by IGJoshua** [comment]
Ah, that does what I want. I hadn't spotted that in the docs yet. Thanks!
