### ISSUE TITLE
Add support for the new VK_KHR_ray_tracing extension

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/ash#277]
See https://www.khronos.org/blog/ray-tracing-in-vulkan

* [ ] Generate vk.rs with the new xml
* [ ] Expose a "high level" extension for `VK_KHR_ray_tracing`
  * I expect this to be a lot of work, a basic version would be good enough for now.

**Comment by msiglreith** [comment]
Relevant PR for reference: https://github.com/MaikKlein/ash/pull/278

**Comment by cheako** [comment]
cmd_build_acceleration_structure() Takes a slice of slice and it's kinda hard to build one of those!  Unless I'm missing some rust foo.

The goal here is to take high level types and add them to the command buffer so they aren't dropped until after the command buffer.
```
    pub fn build_acceleration_structure(
        &self,
        src_acceleration_structure: Option<vk::AccelerationStructureKHR>,
        dst_acceleration_structure: vk::AccelerationStructureKHR,
        pp_geometries: *const *const vk::AccelerationStructureGeometryKHR,
        scratch_data: Buffer<T>,
        info: &[vk::AccelerationStructureBuildGeometryInfoKHR],
        offset_infos: &[&[Buffer<T>]],
    ) {
        let contents = self.contents.borrow_mut();
        let offset_infos: &[&[ash::vk::AccelerationStructureBuildOffsetInfoKHR]] = &offset_infos
            .iter()
            .map(|offset_infos| {
                &offset_infos
                    .iter()
                    .map(|buffer| {
                        contents.push(CommandBufferContents::Buffer(buffer.clone()));
                        vk::AccelerationStructureBuildOffsetInfoKHR::builder()
                    })
                    .collect::<Vec<_>>()[..]
            })
            .collect::<Vec<_>>()[..];
        unsafe {
            self.0
                .ray_tracing
                .cmd_build_acceleration_structure(***self, infos, &offset_infos);
        };
    }
```

**Comment by cheako** [comment]
The type for pp_geometries is wrong...  Can be either *[T] or *[*T].

**Comment by cheako** [comment]
Example: https://gitlab.com/cheako/ash-rt/-/tree/613be44925a56498668367d0ddadd15abdd831b3
It builds, but I don't have the hardware to run it.

**Comment by dylanede** [comment]
Looks like VK_KHR_deferred_host_operations and VK_KHR_pipeline_library need to be added as well since they're dependencies of VK_KHR_ray_tracing, although one can use VK_KHR_ray_tracing without touching functions, structures and flags added by those extensions. Without them I get this message from the validation layer:
```text
Validation Error: [ VUID-vkCreateDevice-ppEnabledExtensionNames-01387 ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x12537a2c | Missing extensions required by the device extension VK_KHR_ray_tracing: VK_KHR_deferred_host_operations, VK_KHR_pipeline_library. The Vulkan spec states: All required extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list (https://vulkan.lunarg.com/doc/view/1.2.148.0/windows/1.2-extensions/vkspec.html#VUID-vkCreateDevice-ppEnabledExtensionNames-01387)
```

**Comment by cheako** [comment]
Perhaps there should be a sticky issue just to track missing extensions...  because there won't exactly be a whole lot of them at any one time.

**Comment by filnet** [comment]
I started working on adding support for the performance_query extension only to realize that my GPU did not support it.
Seems like almost no GPU supports this extension.
