### ISSUE TITLE
Missing cmd_copy_image_to_buffer

### ISSUE THREAD

**Issue by kvark** [MaikKlein/ash#28]
There is `cmd_copy_buffer_to_image` but not the opposite. This is sort of a blocker for me ATM.
Interestingly, documentation [has it](https://docs.rs/ash/0.18.0/ash/vk/cmds/struct.DeviceFnV1_0.html#method.cmd_copy_image_to_buffer) but the code (and published version) does not.

**Comment by MaikKlein** [comment]
`DeviceFnV1_0` are just the "raw" Vulkan function pointers. The wrapped API is exposed in a `Device`. It seems that I haven't exposed this function yet.

I'll do it when I find some time. In the meantime you can always fall back to the "raw" API with by calling `device.fp_v1_0().your_raw_fn`.

**Comment by MaikKlein** [comment]
I'll just quickly do it now.

**Comment by MaikKlein** [comment]
I added it and published a new version.
