### ISSUE TITLE
Missing VK_KHR_sampler_mirror_clamp_to_edge

### ISSUE THREAD

**Issue by kvark** [MaikKlein/ash#281]
Would be great to have this variant in `SamplerAddressMode` as well as the constant extension string. We'd use it in https://github.com/gfx-rs/gfx/issues/2100

**Comment by MaikKlein** [comment]
This is already on master, I'll publish a new version soon!

**Comment by MaikKlein** [comment]
https://docs.rs/ash/0.30.0/ash/vk/struct.SamplerAddressMode.html#associatedconstant.MIRROR_CLAMP_TO_EDGE
