### ISSUE TITLE
Origin of `get_hwnd()` on `winit::Window`

### ISSUE THREAD

**Issue by kulicuu** [MaikKlein/ash#299]
Hello, I've been learning Ash coming from Vulkano.  I was working with the vulkan-tutorial-rust which uses Ash, but with newer versions of things encountered breaking changes and have been checking out Ash's own example.  I am puzzled by a line 166 in lib.rs, `let hwnd = window.get_hwnd() as HWND;`

Winit's `winit::Window` (at version 19.5) has no such function `get_hwnd()`, so where does that come from ?  By the way, I would like to get this working so am interested in clues to how to generate the hwnd to pass to the creation info constructor.

**Comment by zedrian** [comment]
Hi @kulicuu,
**Winit** version 0.19.5 has `winit::os::windows::WindowExt` trait that adds `get_hwnd()` function to `winit::Window` (https://docs.rs/winit/0.19.5/i686-pc-windows-msvc/winit/os/windows/trait.WindowExt.html). It was imported to visible space at line 164 in lib.rs so the compiler understood which function to call there.
I'm currently using latest **Winit** (0.22.1) and it has slightly changed `winit::platform::windows::WindowExtWindows` trait that adds both `hwnd()` and `hinstance()` methods to `winit::Window`.

**Comment by kulicuu** [comment]
Thanks very much, that was very obscure but the direction my research was tending.  Thanks!
