### ISSUE TITLE
AccelerationStructureBuildGeometryInfoKHRBuilder::geometries ergonomics

### ISSUE THREAD

**Issue by zakarumych** [MaikKlein/ash#301]
[AccelerationStructureBuildGeometryInfoKHRBuilder::geometries](https://docs.rs/ash/0.31.0/ash/vk/struct.AccelerationStructureBuildGeometryInfoKHRBuilder.html#method.geometries) should accept `&'a &'a AccelerationStructureGeometryKHR` instead of `&'a *const AccelerationStructureGeometryKHR`.

Loosing lifetime here cost me half a hour of wondering what is going on because I accidentally assigned reference to temporary pointer here.
This was especially bad because just an hour ago I found bug in validation layer that caused similar crash.

**Comment by MarijnS95** [comment]
I agree, that fits the lifetime-preserving shtick of the builders, and should be doable without any copies because `&'a AccelerationStructureGeometryKHR` is not a fat pointer.
