### ISSUE TITLE
WriteDescriptorSetBuilder's buffer_info is the wrong type

### ISSUE THREAD

**Issue by colinmarc** [MaikKlein/ash#306]
The builder for [`WriteDescriptorSet`](https://docs.rs/ash/0.31.0/ash/vk/struct.WriteDescriptorSetBuilder.html#method.buffer_info) seems to be generating incorrectly. The following code fails in the SDK validation layer:

```rust
let buffer_info: vk::DescriptorBufferInfo = ...

let write = vk::WriteDescriptorSet::builder()
                ...
                .buffer_info(&[buffer_info[)
                .build();

...
device.update_descriptor_sets(&[writes], &vec![]);
```

It's hard to explain the validation error because I don't really understand what's going on, but it seems to have to do with the type of `pBufferInfo`, which is being translated into a slice argument and written as an array even though [it's meant to be a single pointer](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkWriteDescriptorSet.html). If I run the above code while running the api dump layer, I get something like:

```
            pBufferInfo:                    const VkDescriptorBufferInfo* = 0x7ffeec258ff0
                pBufferInfo[0]:                 const VkDescriptorBufferInfo = 0x7ffeec258ff0:
                    buffer:                         VkBuffer = 0x7fff903a6780
                    offset:                         VkDeviceSize = 140250333771088
                    range:                          VkDeviceSize = 140735613130592
```

Note that the values are garbage. If I instead set `p_buffer_info` directly:

```rust
let mut write = ...
write.p_buffer_info = &buffer_info
```

Then the code runs, and the api dump looks correct, too:

```
pBufferInfo:                    const VkDescriptorBufferInfo* = 0x7ffee3f4ef50
```

Thanks in advance! The bindings are buttery smooth otherwise.

**Comment by colinmarc** [comment]
I also just noticed that the builder is missing a `descriptor_count` method. That might be related to it thinking that `buffer_info` is an array.

**Comment by aloucks** [comment]
`buffer_info` is in fact an array:

> `descriptorCount` is the number of descriptors to update (the number of elements in pImageInfo, **pBufferInfo**, or pTexelBufferView

Here's how it's implemented:

```rust
    pub fn buffer_info(
        mut self,
        buffer_info: &'a [DescriptorBufferInfo],
    ) -> WriteDescriptorSetBuilder<'a> {
        self.inner.descriptor_count = buffer_info.len() as _;
        self.inner.p_buffer_info = buffer_info.as_ptr();
        self
    }
```

Are you calling `build()` by chance? The build method is not safe due to discarding the lifetimes. It's possible to create pointers to the stack without the `unsafe`  keyword here.

**Comment by colinmarc** [comment]
Ah, yeah, the issue is with `build`. Identical to #192. Thanks!

**Comment by Ralith** [comment]
To clarify:

> The build method is not safe due to discarding the lifetimes.

Calling `build` is always safe; that is why it is not marked `unsafe`. Inspecting the generated code will reveal it doesn't contain any `unsafe` blocks even transitively, so it would be pretty difficult for it to be unsafe.

> It's possible to create pointers to the stack without the unsafe keyword here.

It's possible to do that in any safe rust code without any particular effort. That's what happens any time you use `&foo` to initialize a value of raw pointer type. Constructing raw pointers to anywhere is harmless; you can even do it from arbitrary `usize`s. It's dereferencing them, or passing them to an interface that may dereference them, that's unsafe.

**Comment by colinmarc** [comment]
I know that this has been discussed elsewhere, but what would be the (breaking) API change to prevent people running into this problem? For example, could the builder objects actually take ownership of the structs/vecs passed into them?

**Comment by Ralith** [comment]
Unfortunately it's very difficult to do better than the status quo. For example, taking ownership doesn't work because you may not *have* ownership of the data in question to begin with, e.g. if it's persistent storage that gets reused in the next frame.

**Comment by colinmarc** [comment]
Do you have an example of that? I couldn't find one in my code. Correct me if I'm misunderstanding, but the handles are `Copy`able. So in the example above, the `VkBuffer` isn't being free'd, and neither is the buffer itself; just the array of handle objects. The builder could easily hold on to a vec of those.

**Comment by Ralith** [comment]
> Do you have an example of that?

Not off the top of my head. I mostly pass slices of array literals, which could in principle be replaced by passing owned arrays. Still, it's not in the spirit of ash to make it difficult to execute an efficient pattern that you could reasonably apply in C/C++.

> The builder could easily hold on to a vec of those.

Holding a `Vec` internally means forcing heap allocations on users, which in an extremely performance-oriented API like Vulkan is a dubious proposition. A higher-level library that trades off some performance in favor of safety could more reasonably do such a thing; wgpu might be of interest if that sounds appealing.

**Comment by aloucks** [comment]
> Calling build is always safe; that is why it is not marked unsafe. 

@Ralith We seem to discuss this every few months. My impression is that you're taking a purely academic stance rather than a pragmatic one. The reality is that this issue keeps coming up and people continue to foot-gun themselves with it. 

Casting away the lifetime of a reference by converting it to a pointer is an inherently unsafe thing to do regardless of the keyword. The object in question is passed to native code which hides the fact that its de-referenced in an unsafe way. The existence of the lifetime on the builder structs gives a false sense of safety here. 

Calling the native vulkan function requires `unsafe` anyway and marking build as `unsafe` would be a very clear indication the operation has an unsafe side effect.

**Comment by Ralith** [comment]
> The reality is that this issue keeps coming up and people continue to foot-gun themselves with it.

Whether something is particularly error-prone is almost completely orthogonal to whether it's safe or not. I certainly agree that this is an issue, but claiming incorrectly that build is unsafe only serves to confuse matters.

> Casting away the lifetime of a reference by converting it to a pointer is an inherently unsafe thing to do regardless of the keyword.

When discussing the correctness of Rust code, "unsafe" is generally understood to have a specific concrete meaning. Disregarding that meaning makes it difficult to sensibly discuss correctness.

> The object in question is passed to native code which hides the fact that its de-referenced in an unsafe way.

Dereferencing a raw pointer is *always* unsafe. I disagree that a reasonable reader would ever assume that a raw pointer passed to an unsafe function, in lieu of information to the contrary, would not be dereferenced--to say nothing of that this is probably the *least* subtle correctness issue affecting typical Vulkan calls.

> marking build as unsafe would be a very clear indication the operation has an unsafe side effect.

`build` has no side effects, much less unsafe ones.

**Comment by aloucks** [comment]
> Whether something is particularly error-prone is almost completely orthogonal to whether it's safe or not.

Not when it creates memory safety issues such as pointers to the stack. 

> When discussing the correctness of Rust code, "unsafe" is generally understood to have a specific concrete meaning. Disregarding that meaning makes it difficult to sensibly discuss correctness.

Yes and allowing pointers to the stack to escape a function meets that criteria of "unsafe". You would never accept pure rust code to effectively transmute lifetimes away like this and not consider it unsafe.
