### ISSUE TITLE
Surface creation using ash-window fails on MacOS

### ISSUE THREAD

**Issue by VZout** [MaikKlein/ash#311]
A coworker got the following error on MacOS using the new raw window handle integration:

```
PANIC: "Unable to load create_metal_surface_ext" on "main" in/src/vk/extensions.rs:17772:21
```

**Comment by MaikKlein** [comment]
I think you might have forgotten to call https://docs.rs/ash-window/0.4.1/ash_window/fn.enumerate_required_extensions.html?

**Comment by Friz64** [comment]
Also make sure MoltenVK is up to date.

**Comment by msiglreith** [comment]
Out of interest, what was the solution?

**Comment by VZout** [comment]
Loading the correct extensions. I haven't looked into which extension exactly though. I was not using the extensions functionality from ash-window but our own instead.
