### ISSUE TITLE
Add a linking manifest to link to Vulkan

### ISSUE THREAD

**Issue by kvark** [MaikKlein/ash#312]
This [documentation](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key) implies that Ash should be linking (dynamically) to "vulkan", and also have the corresponding `build.rs` instructions.

This would help NixOS users, for example, see a lengthy discussion at https://github.com/gfx-rs/wgpu-rs/issues/332

Note that technically Ash doesn't have a `-sys` suffix. Perhaps, it would be proper to separate the bindings/generator part into a separate `-sys` crate, e.g. `ash-vulkan-sys`?

**Comment by Ralith** [comment]
NixOS user here. This isn't useful for conventional applications unless winit also makes the same change; winit does *far* more dlopen than ash. It's also easy and fairly routine to use `LD_LIBRARY_PATH` or `patchelf` to work around this issue.

**Comment by Ralith** [comment]
> Perhaps, it would be proper to separate the bindings/generator part into a separate -sys crate, e.g. ash-vulkan-sys?

See also #91. I think we're just manpower-limited on that.

**Comment by Fedcomp** [comment]
> It's also easy and fairly routine to use LD_LIBRARY_PATH

@Ralith it's probably not appropriate to ask here, but how do i do that? (i am beginner nixos user)

The cargo link hint seems to be simple change unlike splitting one crate into two. Can we add vulkan hint in the ash crate for now? The change seems simple, not breaking, and it looks like issue has no progression.

**Comment by Ralith** [comment]
NixOS has a variety of mechanisms to create development environments on demand. I use direnv w/ a shell.nix that includes `shellHook = "export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${stdenv.lib.makeLibraryPath dlopen-libs}"` where `dlopen-libs` is a list of all the packages you want available to `dlopen`, e.g. vulkan and whatever bits of X11 winit wants. Nix flakes are another, unstable, option. There are other approaches I'm less familiar with.

For distribution, the package would invoke `patchelf` during the fixup phase, or apply a wrapper script to set `LD_LIBRARY_PATH`.

**Comment by Fedcomp** [comment]
> You will still need to do this regardless of whether ash links the Vulkan loader unless you aren't using winit or anything similar.

Yes, but if winit add that linking, and ash is not, we still need ash to do that right?

**Comment by Ralith** [comment]
Correct. However, winit is unlikely to do so, as that would make it unable to produce binaries that run on X11 without Wayland installed and vis versa.

**Comment by MarijnS95** [comment]
Ash now supports directly linking against `libvulkan.so` (and relatives on other platforms) since #457, courtesy of @Ralith :tada:
