### ISSUE TITLE
Panic with ERROR_EXTENSION_NOT_PRESENT for VK_KHR_surface

### ISSUE THREAD

**Issue by NickelCoating** [MaikKlein/ash#318]
I can't create a simple device. I seem to have followed the triangle tutorial closely, and it itself runs, yet for some reason [my own code](https://github.com/NickelCoating/tst-create-device) always complains that VK_KHR_surface is missing.

I even used ash-window, but same problem.

I'm running on Windows 10. I can't tell whether it's my code, or an Ash bug.

**Comment by Friz64** [comment]
Instance and device extensions are a seperate thing.
`VK_KHR_surface` is an instance extension and therefore should not be added in the device extensions array.
`VK_KHR_SWAPCHAIN` (for example) is a device extension and should therefore not be added in the instance extension array.

**Comment by NickelCoating** [comment]
Thanks for the help! Yes, you are right. Even the Vulkan tutorial explains this. I thought I could do this small device section without it. -.-

Perhaps it's a case for type safety!? I'm just kidding. I'm closing this...
