### ISSUE TITLE
Missing buffer usage flag VK_BUFFER_USAGE_RAY_TRACING_BIT_KHR

### ISSUE THREAD

**Issue by icanwalkonwater** [MaikKlein/ash#321]
Hi, I just noticed that the flag `VK_BUFFER_USAGE_RAY_TRACING_BIT_KHR` and its cousin `VK_BUFFER_USAGE_RAY_TRACING_BIT_NV` (0x400) are missing from the `ash::vk::BufferUsageFlags` struct.

For reference: [The Vulkan spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkBufferUsageFlagBits.html)

Temporary fix:
```rust
pub trait BufferUsageFlagsExt {
    const RAY_TRACING: vk::BufferUsageFlags = vk::BufferUsageFlags::from_raw(0x00000400);
}

impl BufferUsageFlagsExt for vk::BufferUsageFlags {}
```

**Comment by icanwalkonwater** [comment]
On a similar note the `ash::vk::AccessFlags` struct is also missing the `VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_NV`, `VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_NV` and KHR cousins too.

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAccessFlagBits.html

**Comment by MaikKlein** [comment]
https://docs.rs/ash/0.31.0/ash/vk/struct.AccessFlags.html#associatedconstant.ACCELERATION_STRUCTURE_WRITE_NV and https://docs.rs/ash/0.31.0/ash/vk/struct.AccessFlags.html#associatedconstant.ACCELERATION_STRUCTURE_READ_NV seem to be both there?

**Comment by icanwalkonwater** [comment]
Oh right, they didn't appeared in the source code of this repo nor in CLion.
Guess I should have double checked.
Sorry for the inconvenience.
