### ISSUE TITLE
XCB: Fix xcb_window_t definition

### ISSUE THREAD

**Issue by davll** [MaikKlein/ash#33]
`xcb_window_t` is defined as `*mut c_void`, but it should be `u32` according to `xcb/xproto.h`

**Comment by MaikKlein** [comment]
Interesting, the types of the window handles are not in the `vk.xml` and it seems I just generated *const c_void for every handle because of that. I should define them manually.

**Comment by davll** [comment]
Platform-specific handles should be double-checked manually IMO. :P
Besides, a `Window` in Xlib is actually a pointer-sized integer type (aka `usize`), `*mut c_void` just works fine on x86-64 however.

**Comment by MaikKlein** [comment]
I'll temporarily fix it later today. I am currently writing a generator that generates `vk.rs` from `vk.xml`, I need to make sure that I generate it manually.

I'll keep this issue open for now until I have merged in the new changes.

Thanks for the report!

**Comment by GabrielMajeri** [comment]
@MaikKlein This issue was fixed in #35, and is still fixed in the new `generator` branch, so I think it can be closed?
