### ISSUE TITLE
GgpFrameToken type definition is wrong.

### ISSUE THREAD

**Issue by VorfeedCanal** [MaikKlein/ash#331]
I'm not actually trying to use ASH. I'm trying to parse vk.xml instead.

And also have hit the same issue with NDA-protected GgpStreamDescriptor/GgpFrameToken you did.

But Google actually released SOME information about these types without NDA.

This header here:
  https://github.com/google/gapid/blob/master/core/vulkan/cc/include/ggp_c/vulkan_types.h

It doesn't reveal the internal structure of these types, but is precise enough to pass them without interpreting.

That was enough for my needs, perhaps you can adjust the definition in ASH, too?

**Comment by MaikKlein** [comment]
That seems reasonable for now, I'll add it later today but I haven't decided yet if I want to support private extensions like that in the future.
