### ISSUE TITLE
How to check if a handle is null? 

### ISSUE THREAD

**Issue by nikitablack** [MaikKlein/ash#336]
Hello. Let's take `ash::vk::SwapchainKHR` as an example. How can I check that an instance is `null` or not? Currently, I'm doing `old_swapchain.as_raw() == 0` but how good is that according to best practices? Looking at the source I can't find a better way.

**Comment by filnet** [comment]
You could do `old_swapchain == vk::SwapchainKHR::null()`.
See https://github.com/MaikKlein/ash#strongly-typed-handles.
Not tested...

**Comment by Friz64** [comment]
> You could do `old_swapchain == vk::SwapchainKHR::null()`.
Yup, that would work just fine.

**Comment by nikitablack** [comment]
Yes, this looks better. Thank you.
