### ISSUE TITLE
What does `.clone()` specifically do on Vulkan-Ash objects?

### ISSUE THREAD

**Issue by AndrewHC36** [MaikKlein/ash#337]
This is more of a question on how cloning Vulkan objects work because I am rather reluctant to clone multiple Vulkan objects to find I have to also independently free up each individual clones of that original Vulkan object. I may have miss understood how Vulkan objects are handle, but in what ways how are these Vulkan objects copied?

**Comment by Ralith** [comment]
Ash is a low-level wrapper. Vulkan handles are spiritually similar to raw pointers; with a few exceptions like `Entry` (which is not a Vulkan handle at all) nothing has a `Drop` impl.

**Comment by AndrewHC36** [comment]
So if they are basically raw pointers, does that meaning I can safely assume freeing one of that Vulkan objects will also free up all of that cloned or not cloned Vulkan objects? The same reason why the Ash library is unsafe due to things like this potential giving a dangling pointer?

**Comment by Ralith** [comment]
If you try to use an object identified by a Vulkan handle after freeing it, you will invoke undefined behavior.

**Comment by AndrewHC36** [comment]
Ok thanks!
