### ISSUE TITLE
Window drag has a strange lag with winit 0.23.0

### ISSUE THREAD

**Issue by nikitablack** [MaikKlein/ash#338]
Hello. I'm not sure if this a problem with `ash` or not, but after I upgraded the example to use `winit` version 0.23.0 the window started to have a strange lag during the drag, i.e. when I grab the window and start to move it around this movement is not smooth anymore.

**Comment by Ralith** [comment]
Ash is a thin layer around Vulkan. This is a winit bug, likely specific to whatever platform you're on.

**Comment by nikitablack** [comment]
The behavior is rather strange - if I run the loop without presenting the window can drag smooth. The lag happens only when `queue_present`  is called so the problem relates to `Vulkan` somehow.

**Comment by nikitablack** [comment]
It was my mistake. The wrong `winit` usage. Sorry.

**Comment by simonbuchan** [comment]
@nikitablack I've seen this issue with a simple raw ` loop { while PeekMessage(..., PM_REMOVE) > 0 { DispatchMessage(...) }; draw() }`, but I could only fix it by moving to `std::thread::spawn(move || loop { draw(); }); loop { GetMessage(...); DispatchMessage(...); }` so drawing and messing input happen in parallel, which has it's own issues.

Not sure what change you made in winit usage, but I believe it does a lot of weird nasty stuff to smoothly dispatch messages, without having a separate input thread. Odd that it would have the same symptoms!
