### ISSUE TITLE
Uniform buffer: How am I suppose to translate Rust type and map it to a uniform buffer?

### ISSUE THREAD

**Issue by AndrewHC36** [MaikKlein/ash#340]
The uniform buffer wasn't exactly on the example directory, which I have been heavily relying on when there's Rust vs C types involves. So I was rather not confident with myself to directly map a *Rust* struct type to a buffer from a *C* API. Do I just do the same thing for the uniform buffer using `ash::util::Align` as same as creating vertex buffer, except when it requires to be updated? And can I safely assume that `[[f32;4];4]`  will become `mat4` type once in the shader program?

And also a side note, why does creating multiple uniform buffers increases performance?

**Comment by Ralith** [comment]
[bytemuck](https://crates.io/crates/bytemuck) is useful for converting rust types into bytes. I recommend consulting general Vulkan resources for Vulkan questions; ash is just a very thin wrapper.

**Comment by AndrewHC36** [comment]
I mean I thought Rust types and `ash` buffer creation does have some large differences between the C/C++ tutorial. Nevertheless, thanks! I will keep in mind of that.

**Comment by Ralith** [comment]
There should be no significant differences pertaining to use of Vulkan specifically.
