### ISSUE TITLE
Remove lazy_static dependency

### ISSUE THREAD

**Issue by kvark** [MaikKlein/ash#359]
Do we have to have `VK_LIB` as a static? Can there be an API exposed for the user to hold it, instead?

**Comment by Ralith** [comment]
Did you open this on the wrong repo? `ash` has no such dependency, nor any such variable.

**Comment by Friz64** [comment]
Looks like #194 already removed `lazy_static` as a dependency. This has been released since version `0.29.0` (Apr 27, 2019).

**Comment by kvark** [comment]
Wonderful news! Bugs that are fixed in the past are best kinds of bugs :) I just had an older copy of Ash, where I saw that, and I didn't check the recent one.
