### ISSUE TITLE
ash::vk::PFN_vkFreeFunction has unfortunate signature

### ISSUE THREAD

**Issue by nicokoch** [MaikKlein/ash#360]
`ash::vk::PFN_vkFreeFunction` is currently defined as 

```rust
type PFN_vkFreeFunction = Option<unsafe extern "system" fn(p_user_data: *mut c_void, p_memory: *mut c_void) -> c_void>;
```

Notice that the return type is `c_void` instead of `()`.
The [c_void](https://doc.rust-lang.org/std/ffi/enum.c_void.html) documentation makes it clear that this is incorrect:

> Equivalent to C's void type when used as a pointer.
>
> In essence, `*const c_void` is equivalent to C's `const void*` and `*mut c_void` is equivalent to C's `void*`. That said, this is not the
> same as C's `void` return type, which is Rust's `()` type.

The current signature sadly makes it impossible to actually provide a `vkFreeFunction` to vulkan (without crazy function pointer casts), because a `c_void` cannot be constructed inside an implementation of type `PFN_vkFreeFunction` .

**Comment by MarijnS95** [comment]
Looks like quite a few functions (even "irrelevant" internal ones) return `c_void` now, should be trivially fixable in the generator :)
