### ISSUE TITLE
Fifo present mode occasionally returns VK_TIMEOUT without blocking in wgpu-rs examples

### ISSUE THREAD

**Issue by Imberflur** [MaikKlein/ash#368]
System Details
```
OS: Manjaro 20.2.1 Nibia
Kernel: x86_64 Linux 5.10.7-3-MANJARO
DE: Xfce4
CPU: Intel Core i5-4690 @ 4x 3.9GHz
GPU: AMD Radeon HD 7900 Series (TAHITI, DRM 3.40.0, 5.10.7-3-MANJARO, LLVM 11.0.1)
drivers tested: radv, amdvlk, vulkan-amdgpu-pro
```
`wgpu` provides a 1s timeout which ends up being passed to `Swapchain::acquire_next_image` however on my system sometimes `VK_TIMEOUT` will be returned within ~20-200µs when using the Fifo present mode. This occurs every few seconds for me on the `wgpu-rs` water example (Note: most of the examples use Mailbox by default so to test this the present mode needs to be changed).

**Comment by Ralith** [comment]
ash is a thin binding to Vulkan. Unless you have specific cause to believe your operations are getting mangled before the driver sees them, you should report this to the vendor instead.

**Comment by kvark** [comment]
That's reasonable. We'll keep tracking this on our side.
