### ISSUE TITLE
ColorSpaceKHR enum only contains one element

### ISSUE THREAD

**Issue by michidk** [MaikKlein/ash#371]
ColorSpaceKHR enum only contains one element: https://docs.rs/ash/0.31.0/src/ash/vk/enums.rs.html#1153-1155
But the spec actually lists quite a few more: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkColorSpaceKHR.html

This is especially relevant if one doesn't want to work in sRGB space.

**Comment by MarijnS95** [comment]
Hi @michidk!

`ash` uses `impl` blocks to extend "enums" with more members for extensions elsewhere:

https://github.com/MaikKlein/ash/blob/dd2849450fca7a6361fa51883bda7a37daf2add5/ash/src/vk/extensions.rs#L8299-L8358

**Comment by michidk** [comment]
Gotcha! Thanks for the explanation!

**Comment by MarijnS95** [comment]
For completeness, they do show up in the documentation as well:

https://docs.rs/ash/0.31.0/ash/vk/struct.ColorSpaceKHR.html
