### ISSUE TITLE
AccelerationStructure and use of vk::Device

### ISSUE THREAD

**Issue by filnet** [MaikKlein/ash#377]
AccelerationStructure holds a vk::Device and some functions use it while other require the vk::Device as an argument.

Is there a reason for that ?

**Comment by MarijnS95** [comment]
That looks to have been yet another porting artifact when migrating to the stable headers. Same applies to `RayTracingPipeline`. It should just be removed from function signatures to match the rest of the functions and extensions. Done so in the attached PR.
