### ISSUE TITLE
Release a new stable version?

### ISSUE THREAD

**Issue by Rua** [MaikKlein/ash#382]
I'm interested in using Ash as a foundation for the Vulkano project ([link](https://github.com/vulkano-rs/vulkano/issues/1500)). Vulkano needs the ability to load custom Vulkan libraries, which I see was added by #319, but not yet published as part of a stable version on crates.io. Would it be possible to release a new stable version sometime soonish, so that this feature becomes available? Thank you!

**Comment by Friz64** [comment]
See also: [This discussion](https://github.com/MaikKlein/ash/discussions/376)

**Comment by Rua** [comment]
Ah, nice! I'll close this then.

**Comment by MarijnS95** [comment]
That's a nice coincidence, I wondered about the same and asked this [just days ago](https://github.com/MaikKlein/ash/discussions/376) but GH discussions are rather hidden, there isn't even an "open discussions" number like there is for issues and PRs...

Things are moving and most open PRs addressing outstanding issues have been merged over the past few days. I'd take this opportunity again to ask @MaikKlein whether there are any outstanding blockers and issues that need to be addressed before the next release can be made. I'm sure the community is willing to expedite these to make it all the way to the end :)

Lastly https://github.com/vulkano-rs/vulkano/issues/1500 sounds really cool! While I'm not the maintainer of Ash I'm sure we can accommodate to changes necessary for Vulkano, and you can always use the C functions directly from `*Fn` structs. Seems like the collaborative effort spent between ash and vulkano is better spent maintaining a single, proper native wrapper crate :tada:!

**Comment by MaikKlein** [comment]
I'll release a new version very soon. I am open for https://github.com/vulkano-rs/vulkano/issues/1500 There have been talks about it a few years ago but nothing has happened yet. Either we move the function pointers to a new crate like ash-sys, or we put more things behind feature flags see https://github.com/MaikKlein/ash/issues/344

**Comment by Rua** [comment]
What do you mean regarding the function pointers? Ash seems quite usable for Vulkano as it is.

**Comment by MaikKlein** [comment]
> Ash seems quite usable for Vulkano as it is.

That is good to hear. Ash currently is a fairly large dependency. It comes with "high level" apis, builders etc. After the generator rewrite, you will be able opt out of most of these.

**Comment by Rua** [comment]
Hmm, is the size a major cause of slow compile times? Vulkano isn't all that fast to compile as it is, so maybe the extra time would disappear in the noise. Besides, cleaner, more idiomatic code in Vulkano might be worth it.

**Comment by MarijnS95** [comment]
Compile-time of ash doesn't seem too bad, and it's only a one-off after clean builds when not actively developing on the crate itself.

Perhaps the CI (individual steps) is a clear enough indicator: https://github.com/MaikKlein/ash/actions?
