### ISSUE TITLE
use bitflags crate

### ISSUE THREAD

**Issue by Pernet** [MaikKlein/ash#396]
Ash uses a [custom macro vk_bitflags_wrapped!](https://github.com/MaikKlein/ash/blob/master/ash/src/vk/macros.rs#L18), that is not specific to Vulkan.
It could instead use bitflags! macro for [generating a more complete rust code](https://docs.rs/bitflags/1.2.1/bitflags/example_generated/struct.Flags.html).
This crate is used by [many other rust projects](https://crates.io/crates/bitflags/reverse_dependencies).

**Comment by Rua** [comment]
What does Ash currently implement for bitflags that the bitflags crate doesn't?

**Comment by MarijnS95** [comment]
Does `bitflags!` require all flags to be defined inside the macro?

That would be a major limitation for Ash and its extensions, where extra variants introduced by an extension are simply added by a loose:

```rust
impl SomeFlags {
    const MyExtensionBits: Self = Self(1_000_extensionnum_flagnum);
}
```

inside `extensions.rs`.

**Comment by MarijnS95** [comment]
One thing to note is that Ash's `fn all()` and `fn is_all()` _only represent core values_. Anything in an extension is not considered. Likewise, the `ops::Not` operator _only flips core bits, not all_!

**Comment by Ralith** [comment]
Which is really weird and counterintuitive. IMO we should get rid of any definitions that don't make sense with extensions.

> That would be a major limitation for Ash and its extensions

The generator could be refactored to not do this, of course.

**Comment by MarijnS95** [comment]
> IMO we should get rid of any definitions that don't make sense with extensions.

@Ralith I don't think I fully understand what you mean. Indeed, `::all()` not returning every bitflag that we know about is just plain wrong. We shouldn't get rid of the definitions with extensions, rather they should be moved into `bitflags.rs` with their summed value properly represented. The `bitflags` crate can do this for us as well.

I guess this is something to consider for `generator2`, I don't know how @MaikKlein intends to split output files there. Being able to have beta extensions completely behind a feature toggle would be a nice feat too.

**Comment by Ralith** [comment]
> Indeed, ::all() not returning every bitflag that we know about is just plain wrong.

The problem is, this will always be true for any definition of `all` other than `!0`, because new extensions will be defined in the future, and programs written using current ash will need to be well behaved in an environment that supports them.

**Comment by MarijnS95** [comment]
The best we can do is provide bits that we know about given the header version Ash was generated against, prematurely returning `!0` defeats the purpose entirely. The only usecase might be knowing whether a bit was set that is unknown in this version of Ash, hence being outdated? It should be known (or documented) that `::all()` returns all bits Ash knows about rather than all bits that are supported depending on the current instance/device - that makes no sense.

FWIW I've never had to use this function anyway in favour of explicitly specifying all bits or using Vulkan's explicit `ALL_*` flags. We might as well drop the `all()` function entirely if there's no true meaning in this context.

**Comment by Rua** [comment]
Unfortunately, the bitflags crate includes an `all` function, and some other things like `not` rely on it.

**Comment by Ralith** [comment]
> We might as well drop the all() function entirely if there's no true meaning in this context.

Yes, that was my point. It's not really a sensible thing to try to provide.

> Unfortunately, the bitflags crate includes an all function, and some other things like not rely on it.

Sounds like we shouldn't use it, then, unless it can be made optional. That's fine.

**Comment by MaikKlein** [comment]
Yes lets remove `all`, there is no sensible default for it. (Optin would be fine)

> It could instead use bitflags! macro for generating a more complete rust code.

Is there anything missing in the current bitflags in ash that you would like to have?

**Comment by Pernet** [comment]
There is nothing I could think of that requires bitflags. It's just a matter of having your feelings about your choice of creating your own version. I have had an acceptable answer with all these commentaries. Maybe, add some code comments to explain why Ash should not have an "all" function ?
