### ISSUE TITLE
LoadingError exposed but private

### ISSUE THREAD

**Issue by mikedilger** [MaikKlein/ash#4]
I can't do:
````rust
let entry = Entry::new()?;
````
because I can't wrap your error type.

Also, `ash::vk::Result` neither implements `std::error::Error` nor `std::fmt::Debug`, both of which would be useful.

All of this is minor, but also minor to fix I think.

**Comment by MaikKlein** [comment]
Thanks for the report, I'll fix it tomorrow.

**Comment by mikedilger** [comment]
Ah, I see LoadingError was exported on Jan 9th, just not published.  DeviceError has same issue, I submitted a PR.

**Comment by MaikKlein** [comment]
Thanks for the PR, I was pretty busy the last couple of days. [vk::Result](https://github.com/MaikKlein/ash/blob/master/src/vk.rs#L2634) implement at least debug. Do you also want it to implement `std::error::Error`?

**Comment by mikedilger** [comment]
Nah, doesn't really matter.
