### ISSUE TITLE
Expose `copy_query_pool_results`

### ISSUE THREAD

**Issue by kvark** [MaikKlein/ash#404]
It was added in #105, but still not exposed directly (only via the function pointers)

**Comment by MarijnS95** [comment]
Isn't this exposed in the safe `Device` API already?

https://github.com/MaikKlein/ash/blob/8444db4fb2887c86dc87533fc20b85a0a5da1233/ash/src/device.rs#L1381-L1408

**Comment by kvark** [comment]
Apologies for misnaming the issue. It's about `copy_query_pool_results`.

**Comment by MarijnS95** [comment]
@kvark Does such a function even exist? `vkCopyQueryPoolResults` surfaces nothing, there's only `vkCmdCopyQueryPoolResults` which is _also_ exposed on the `Device`:

https://github.com/MaikKlein/ash/blob/8444db4fb2887c86dc87533fc20b85a0a5da1233/ash/src/device.rs#L1128-L1150

**Comment by MaikKlein** [comment]
This one? https://docs.rs/ash/0.32.0/ash/version/trait.DeviceV1_0.html#method.cmd_copy_query_pool_results

**Comment by kvark** [comment]
Yes, it should be on a command buffer

**Comment by MaikKlein** [comment]
> Yes, it should be on a command buffer

As a method on a commandbuffer? Ash doesn't do that. All high level functions are on instance and device.

**Comment by kvark** [comment]
Hmm, perhaps, I overlooked this. Thank you for clarification!
