### ISSUE TITLE
ash::vk::make_version should be deprecated and ash::vk::make_api_version should take its place

### ISSUE THREAD

**Issue by AlexApps99** [MaikKlein/ash#428]
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_MAKE_VERSION.html
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_MAKE_API_VERSION.html

**Comment by MarijnS95** [comment]
This only becomes relevant when Vulkan 1.2.175 is supported by Ash, where this deprecation happened. The current open PR for that [silently makes the deprecated ones disappear](https://github.com/MaikKlein/ash/pull/417/files#diff-de84e0b739496d075bbbbe18e9ff5c7b444f0b8bfe2160b07c998ead1b200844L9-R10).

I've been playing around with autogenerating `#define`s including proper handling of links and deprecation warnings, and the result is pretty neat IMO: https://github.com/MaikKlein/ash/commits/autgenerate-define-exprs. The code may be a bit brittle, but that should be okay given that this generator is on its way out again. More interesting, regenerating `.175` with this method puts everything in the right spot automatically: https://github.com/MaikKlein/ash/commit/0c2906680bed81f99401b267105c2e0525a76200#diff-de84e0b739496d075bbbbe18e9ff5c7b444f0b8bfe2160b07c998ead1b200844R9-R57
