### ISSUE TITLE
 LICENSE-* files missing in crates.io

### ISSUE THREAD

**Issue by jmacnak** [MaikKlein/ash#453]
This prevents the project from being used in some projects.

**Comment by jmacnak** [comment]
See #452 .

Could we also re-publish after #452 is merged?

**Comment by jmacnak** [comment]
Can you publish a new version to crates.io so that LICENSE files appear in the published crate?

**Comment by MarijnS95** [comment]
@jmacnak We're scheduling a new release for at least two months now, it'll come around at some point :wink:
