### ISSUE TITLE
`ClearValue` can be fixed now?

### ISSUE THREAD

**Issue by icefoxen** [MaikKlein/ash#46]
`ClearValue` is described as "Temporary Hard-Coded union hack; will be automatically generated when actual unions become stable" here: https://docs.rs/ash/0.21.0/ash/vk/types/struct.ClearValue.html

Unions are stable now, I believe, so can this be fixed?

Thanks a lot for ash btw, it's pretty darn great.

**Comment by MaikKlein** [comment]
Thanks for reminding me, I am going to address this today.

**Comment by MaikKlein** [comment]
Done https://github.com/MaikKlein/ash/commit/1b612cb1bffd4bd13ab076af7214f03c9cc24cc2
