### ISSUE TITLE
Support for a statically linked vulkan library

### ISSUE THREAD

**Issue by lucypero** [MaikKlein/ash#462]
My platform's Vulkan driver is a static library. How do I plug that with ash?

**Comment by MaikKlein** [comment]
It is currently being worked on https://github.com/MaikKlein/ash/pull/457. Otherwise you can have a look at https://github.com/EmbarkStudios/ash-molten/blob/main/src/lib.rs to see how it links with moltevk.

**Comment by MarijnS95** [comment]
For `ash-molten` you can effectively add `println!("cargo:rustc-link-lib=static=./path/to/your/libvulkan.a");` as suggested [here](https://github.com/EmbarkStudios/ash-molten/pull/56#issuecomment-877034275) (note that that PR is required on Ash 0.33 going forwards) in `build.rs` for your respective platform, and we'll probably try to figure out how to make dynamic and static linking as configurable as possible in #457, linked above already.
