### ISSUE TITLE
VK_INCOMPLETE returned by enumerate_instance_extension_properties

### ISSUE THREAD

**Issue by kvark** [MaikKlein/ash#464]
Downstream - https://github.com/gfx-rs/wgpu/issues/1768
Ash code - https://github.com/MaikKlein/ash/blob/d6e049f340e0b0ed8a17ff5de55a8500bbe0b534/ash/src/instance.rs#L405
Looks like the spec isn't guaranteeing that the `count` is enough:

> Because the list of available layers may change externally between calls to `vkEnumerateInstanceExtensionProperties`, two calls may retrieve different results if a `pLayerName` is available in one call but not in another. The extensions supported by a layer may also change between two calls, e.g. if the layer implementation is replaced by a different version between those calls.

Not sure who'd be responsible to rule that out. Would it be completely nuts to do this query in a loop until it succeeds?

**Comment by Ralith** [comment]
> Would it be completely nuts to do this query in a loop until it succeeds?

This is generally the correct way to implement the two-call pattern, yeah. We should do that in every instance (ideally via a helper).
