### ISSUE TITLE
build fails on --release

### ISSUE THREAD

**Issue by xerauquil** [MaikKlein/ash#468]
The rust compiler finds a lot of error when trying to build with --release

[cargo build --release output](https://pastebin.com/wPmwixD9)

**Comment by MarijnS95** [comment]
I think you accidentally edited one of the crate files while browsing the downloaded source (`/home/dir/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.32.1/src/vk/enums.rs:873:1`), and the crate is only being recompiled for your in `--release`. There's an erroneous `w` inserted here that is not present in Ash at all:

```rust
error[E0412]: cannot find type `Result` in module `vk`
    --> /home/dir/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.32.1/src/device.rs:1503:60
     |
1503 |     ) -> Result<Vec<vk::Pipeline>, (Vec<vk::Pipeline>, vk::Result)> {
     |                                                            ^^^^^^
     | 
    ::: /home/dir/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.32.1/src/vk/enums.rs:873:1
     |
873  | pub struct wResult(pub(crate) i32);
     | ----------------------------------- similarly named struct `wResult` defined here
     |
help: a struct with a similar name exists
     |
1503 |     ) -> Result<Vec<vk::Pipeline>, (Vec<vk::Pipeline>, vk::wResult)> {
     |        
```

It builds successfully for me on `--release`, and such a mistake would have broken the CI on debug as well.

**Comment by MarijnS95** [comment]
You can remove the `w`, or delete the whole crate (`rm -r .cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.32.1/`) and let `cargo` redownload a fresh copy.

**Comment by xerauquil** [comment]
That seems to be the issue. My bad :sweat_smile: . Thank you.
