### ISSUE TITLE
Triangle & Texture example crashing when hovering with the mouse over them 

### ISSUE THREAD

**Issue by 187Qrly** [MaikKlein/ash#471]
Hey,

As you can see in the Title, exactly this is the problem. Here is a Video demonstraiting this: https://youtu.be/NoU_qpz5hlc

I made a neofetch in the video, which shows my specs. 
Here is the Log when running: https://pastebin.com/yK3B2PDK
Here is my output of the vulkaninfo command: https://pastebin.com/daLq9HVQ

I want to start learning Vulkan, so I nearly know nothink about it. So, if I forgot to show somethink, 
just say it and I will give you the info.

Thanks.

**Comment by MaikKlein** [comment]
> thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid'

That seems like it might be a winit bug

**Comment by MarijnS95** [comment]
This issue has also been reported in #345 and #419, and should be addressed in #356. Unfortunately that PR changes a substantial amount of code besides simply bumping winit to a newer version (which has some problems of its own), making it unattractive for reviewers.

**Comment by 187Qrly** [comment]
So I need to report that over at winit?

**Comment by 187Qrly** [comment]
Somome has the same problem?

**Comment by 187Qrly** [comment]
I dont know if thats important, but the examples are using an outdated version of winit:
winit = "0.19.5", but the newest version is 0.25.0

**Comment by Ralith** [comment]
winit has already fixed this issue in more recent versions but the current example code is very old, and does not illustrate good practices in the first place; you're best off learning from other resources, e.g. https://vkguide.dev/. No action from you is needed.

**Comment by 187Qrly** [comment]
Ok, Thank you very much, I will learn rust with ash now.  Sorry, I forgot to close this :)
