### ISSUE TITLE
What parts of the spec are missing?

### ISSUE THREAD

**Issue by LPGhatguy** [MaikKlein/ash#50]
In the README, I noticed that this was in progress:

> * Wrapping the complete spec

How is the wrapper generated? What parts of the spec are missing that still need to be wrapped, and should we automate generation of those parts?

As a side question, what patch number is Ash correct up to, and should that be more publicly exposed?

**Comment by MaikKlein** [comment]
>How is the wrapper generated? What parts of the spec are missing that still need to be wrapped, and should we automate generation of those parts?

`vk.rs` was generated some time ago, that is the low level part. I still need to write a new generator but I haven't found the time to do it yet. The rest is written by hand. I think probably 90% of the spec is exposed atm.

>As a side question, what patch number is Ash correct up to, and should that be more publicly exposed?

Do you mean the patch number of Vulkan? Ash can be used with the newest version Vulkan, just some of the newest extensions aren't exposed yet.

**Comment by MaikKlein** [comment]
Also if something is missing, 100% of the spec is exposed as raw function pointers. https://docs.rs/ash/0.22.0/ash/vk/cmds/struct.DeviceFnV1_0.html

**Comment by LPGhatguy** [comment]
Is there a reason why Ash can't use an existing generator like `vk_generator`? https://github.com/Osspial/vk-rs

It looks to be maintained again after being silent for a year.
