### ISSUE TITLE
`SubpassDescriptionBuilder::resolve_attachments` Must null Out the Pointer if Slice Length is 0

### ISSUE THREAD

**Issue by cwfitzgerald** [MaikKlein/ash#508]
Currently the builder for the resolve attachments just takes the pointer of the slice of the resolve attachments. Unfortunately the spec requires this be a true null if there are no resolve attachments. 

> pResolveAttachments is NULL or a pointer to an array of colorAttachmentCount VkAttachmentReference structures defining the resolve attachments for this subpass and their layouts.

Which means the generated code should look something like:

```rust
    pub fn resolve_attachments(mut self, resolve_attachments: &'a [AttachmentReference]) -> Self {
        self.inner.color_attachment_count = resolve_attachments.len() as _;
		if self.inner.color_attachment_count != 0 {
        	self.inner.p_resolve_attachments = resolve_attachments.as_ptr();
		} else {
			self.inner.p_resolve_attachments = 0 as _;
        }
        self
    }
```

Unfortunately it is _just this_ slice that needs that qualification added.

This has caused a real driver issue on mobile drivers.

**Comment by cwfitzgerald** [comment]
Not an ash bug, misread the spec. This is a driver bug, and per precident, will be worked around a layer above ash.

**Comment by MarijnS95** [comment]
Related: https://github.com/MaikKlein/ash/issues/445
