### ISSUE TITLE
Support LunarG Vulkan SDK for macOS

### ISSUE THREAD

**Issue by yvt** [MaikKlein/ash#51]
LunarG Vulkan SDK supports macOS [starting from 1.0.69](https://vulkan.lunarg.com/doc/sdk/1.0.69.0/mac/getting_started.html). This SDK includes `libvulkan.1.dylib`, the fully-functioning official loader library, as well as MoltenVK ICD, standard validation layers, and their JSON definition files.

Since `libvulkan.1.dylib` provides more functionality and flexibility than loading MoltenVK directly does, maybe it’s a good idea to load it by default in place of `libMoltenVK.dylib`?

**Comment by MaikKlein** [comment]
I assume it is the same thing, and `ash` only needs `vkGetInstanceProcAddr`. I guess it would make sense to switch to the new naming scheme for now but In the future I will implement a new loader where you can explicitly specify the dll that you want to load.

**Comment by termhn** [comment]
Gaining support for validation layers and debug extension stuff is a big plus, and needed to make examples run without adding a bunch more macOS-only modifications to disable the validation layers and debug extension which are not supported by raw MoltenVK.
