### ISSUE TITLE
DynamicRendering builder in release

### ISSUE THREAD

**Issue by pmathia0** [MaikKlein/ash#510]
Hello,
I'm trying to use the new dynamic rendering extension.
In Debug mode of my application, while using builder pattern for vk::RenderingInfoKHR and vk::PipelineRenderingCreateInfoKHR, everything works fine.
However, running the application in Release mode fails.
I found a solution to that: instead of using builder pattern for the structures mentioned above, I create them manually and initialize each field by hand, avoiding Default trait.
Therefore question is: is there something broken in builder patterns for this extension or am I missing something?

**Comment by Ralith** [comment]
Have you read the doc comment attached to every `build` function?

**Comment by pmathia0** [comment]
Can you ellaborate pls

**Comment by pmathia0** [comment]
I see. If I don't use `build`, I get an error: `temporary value dropped while borrowed
consider using a `let` binding to create a longer lived value`, which helped me fix the issue on my side.
What a coincidence, I use builders everywhere and only this one caused problems
Sorry for opening new issue.

**Comment by aloucks** [comment]
> Have you read the doc comment attached to every build function?

@Ralith How many of these need to pop up before we fix this :)

**Comment by Ralith** [comment]
I am overwhelmingly skeptical that adding a strictly meaningless `unsafe` to a function which is unlikely to be called anywhere but inside an unsafe block will cause people who didn't read the docs to do so.

In any case, we want to get rid of the notion of builders as a separate type entirely at this point, which moots the whole debate.
