### ISSUE TITLE
Don't require explicitly linking libvulkan by default

### ISSUE THREAD

**Issue by Jasper-Bekkers** [MaikKlein/ash#525]
> Yes, the build environment will need to have a libvulkan for the target available. IMO it's a reasonable default. For one thing, the linker error you get for a missing foreign library is highly recognizable and easy to google, with the same solution across all programming languages, whereas a build error due to not having default features would be more idiosyncratic.

I'll resurrect this thread now that ash 0.34 is out and we're starting to see the first linker errors across our crates. I think this may have been a mistake. Rust users aren't used to fixing (or seeing) linker errors, and I honestly think this is a bad precedent to set from a usability point of view.

_Originally posted by @Jasper-Bekkers in https://github.com/MaikKlein/ash/issues/457#issuecomment-999941199_

**Comment by Jasper-Bekkers** [comment]
Posted here for visibility since I don't think the old PR gets much attention anymore most likely. See the rest of the PR where @aloucks also brings up some good points on why this is a mistake.

Honestly one of the power of rust is not having to have to fight with linker errors etc, and having easy portability to other platforms without having to set up different build configs for them, having to do steps differently just for linux is frustrating and (frankly) annoying.

Over in the gpu-allocator repo we've already seen first instances of this idea/change backfiring when an unaware community member contributed an upgrade to ash 0.34 which triggered linker errors in our CI (honestly - I suspected the CI setup was broken because of it).

I personally don't think having libloading as a dependency is that bad - the dependency easily hides in the build tree of the rest of the project (most likely it's included in there already anyway), and it's not where the `ash` build time issues are actually coming from either.

**Comment by Ralith** [comment]
Thanks for opening an issue! While there is extensive Rust ecosystem precedent for linking to external libs, if people are finding the CI changes required to be onerous, I don't have a strong objection to rolling back the default features. Would you also prefer that we rename `Entry::new` to `Entry::linked` and `Entry::load` to `Entry::new` to recover a degree of source compatibility with 0.33?

> having to do steps differently just for linux is frustrating

The requirements for Linux and Windows are the same: the Vulkan library must be available. If anything I found this to be more difficult on Windows, where the SDK installer must be downloaded, executed or extracted, and exposed to the CI environment, whereas on Linux it's just an apt-get away.

**Comment by MaikKlein** [comment]
It is often hard to get good feedback when a feature is designed. Thanks for reaching out @Jasper-Bekkers @aloucks .

If we were to revert how would we do it? Yank the old release?

> Would you also prefer that we rename Entry::new to Entry::linked and Entry::load to Entry::new to recover a degree of source compatibility with 0.33?

Personally I quite like the explicitness of ` Entry::linked` and ` Entry::load`

**Comment by Ralith** [comment]
> Yank the old release?

Yanking is only required if there's a soundness or security issue; we should just push a new release.

**Comment by Ralith** [comment]
Drafted https://github.com/MaikKlein/ash/pull/526.

**Comment by MarijnS95** [comment]
> Honestly one of the power of rust is not having to have to fight with linker errors etc, and having easy portability to other platforms without having to set up different build configs for them, having to do steps differently just for linux is frustrating and (frankly) annoying.

Tbh it's very similar to runtime loading, both need an annoying name-dance (but Windows excels here with its `.lib` files). The only difference being that we can be more lenient in setting custom paths, search directory trees, and gracefully abort with a helpful message if all else fails.

That said I don't think `libloading` is particularly a bad thing, rather dynamic linking being equally good depending on the use-case. The comments must be focused on Windows which totally sucks in this regard, libraries are installed wherever and GLHF finding them through ancient and many-times-renamed environment variables (looking at CMake detection modules :astonished:). On Linux it's much easier to deal with and ie. package managers/builders extract helpful dependency info from `ldd`.

---

However, the main reason I think this should not be the default is _library_ crates. Our `gpu-allocator` is a prime example: that crate needs no `Entry` loading/linking whatsoever as it expects a full loaded `&ash::Device` with function pointers. For the `loaded` feature that's easy: just don't call the `load()` function and everything is fine, even if an unused dependency shows up in the crate graph.
Not so much for `linked`, as this crate will now force every binary (executable and `cdylib`) to be linked against `libvulkan` even if that crate opts to disable default features and go with `loaded` instead.
As such, one could even argue that we shouldn't enable either feature by default (but document very clearly in the readme how to choose one of the features). However, it seems `ash` is mostly consumed by projects that directly wish to use Vulkan so we shouldn't cater to the few library-only crates.

**Comment by Ralith** [comment]
Library crates should almost always set `no-default-features` for their own dependencies, but that wouldn't help much with CI since end-to-end binary examples will still need to be buildable. I considered arguing for having neither default, but it seems like a shame to practically guarantee every new user suffer a papercut.

**Comment by MarijnS95** [comment]
Then I've seen a lot of libraries exercise bad practice :grin:

**Comment by Ralith** [comment]
Yeah, that's unfortunately inevitable, so handling it with relative grace is nice.
