### ISSUE TITLE
Helper function for rgba `vk::ColorComponentFlags`

### ISSUE THREAD

**Issue by expenses** [MaikKlein/ash#536]
with the removal of `vk::ColorComponentFlags::all()`, I tried to use `!vk::ColorComponentFlags::empty()`. This causes a vulkan validation error:

`
VUID-VkPipelineColorBlendAttachmentState-colorWriteMask-parameter(ERROR / SPEC): msgNum: -1191591886 - Validation 
Error: [ VUID-VkPipelineColorBlendAttachmentState-colorWriteMask-parameter ] Object 0: handle = 0x1e7895b3b98, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xb8f9c032 | vkCreateGraphicsPipelines: value of pCreateInfos[9].pColorBlendState->pAttachments[0].colorWriteMask contains flag bits that are not recognized members of VkColorComponentFlagBits The Vulkan spec states: colorWriteMask must be a valid combination of VkColorComponentFlagBits values (https://vulkan.lunarg.com/doc/view/1.2.198.0/windows/1.2-extensions/vkspec.html#VUID-VkPipelineColorBlendAttachmentState-colorWriteMask-parameter)
`

It'd be great to have a `vk::ColorComponentFlags::rgba()` helper function for this.

**Comment by MaikKlein** [comment]
@MarijnS95 Do you remember why we kept negation for bitflags? That seems wrong without `all`.

**Comment by MarijnS95** [comment]
@MaikKlein All discussion happened in the original PR, for example: https://github.com/MaikKlein/ash/pull/478#issuecomment-964600807.

IMO `not()` is more correct now that it does not source from known extension bits anymore, which is just a snapshot at the time `ash` was generated.
