### ISSUE TITLE
Using builders with conditional blocks

### ISSUE THREAD

**Issue by dawsonc623** [MaikKlein/ash#540]
I hope this is the right place for this issue. I have been using `ash` for a while now and loving it. I was originally using raw structures instead of builders (simply due to ignorance), but I switched my code over to use builders instead. However, I ran into an issue in the following style of code:

```
// Instance create info

let create_info = vk::InstanceCreateInfo::builder()
    .application_info(&application_info)
    .enabled_extension_names(desired_extension_names)
    .enabled_layer_names(desired_layer_names);

// Enable debug messaging if requested

if let Some(debug_messenger_create_info) = debug_messenger_create_info {
    create_info.push_next(debug_messenger_create_info);
}

// Instance

let instance = unsafe {
    entry
        .create_instance(&create_info, None)
        .expect("failed to create Vulkan instance!")
};
```

`debug_messenger_create_info` is an `Option<DebugUtilsMessengerCreateInfoEXTBuilder>` mutable reference in this case. The idea for the function this code is contained in is to pass in a builder in debug mode and `None` in release. What happens, though. is the `.create_instance(&create_info, None)` line fails because `create_info` is moved when used in the conditional.

I am not the most adept at either Vulkan or Rust, so this could just be my ignorance again. However, I am curious if this is a case that should be supported and how one would go about supporting it.

**Comment by expenses** [comment]
You want

```rust
let mut create_info = ...;
```
and

```rust
create_info = create_info.push_next(debug_messenger_create_info);
```

Instead.

**Comment by dawsonc623** [comment]
@expenses You are my hero. Thank you so much!
