### ISSUE TITLE
Loss of window events when FIFO presentation mode is used

### ISSUE THREAD

**Issue by lwjglgamedev** [MaikKlein/ash#541]
I0m not sure if this is an issue of ash or a wininit one. When switching the presentation mode of the examples, for example the trinmagle one, from MAILBOX to FIFO, the window seems not to be responding to the events (youc annot drag it or even close it properly). I'm performing the tests with Windows 11.

**Comment by Ralith** [comment]
ash is not involved in delivery or handling of Windows events; I recommend opening an issue on winit.

**Comment by lwjglgamedev** [comment]
The thing is why this happens when siwtcihng form MAILBOX to FIFO. Testing with pure winit code code does not show this behaviour. Any ideas?

**Comment by Ralith** [comment]
Probably something to do with the DXGI's internals. It's winit's responsibility to deal with in any case.

**Comment by lwjglgamedev** [comment]
Thanks for the response, I will open an issue in winiti's repo.
