### ISSUE TITLE
Missing `VK_COLOR_SPACE_DCI_P3_LINEAR_EXT`

### ISSUE THREAD

**Issue by Rua** [MaikKlein/ash#548]
This enum variant was recently renamed to `VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT` in Vulkan, but the old name was kept as an alias. In Ash 0.35 though it seems only the new name is available, even though I believe Ash's practice is to include aliases as well?

**Comment by MarijnS95** [comment]
#502
