### ISSUE TITLE
Vulkan 1.3 support

### ISSUE THREAD

**Issue by Sable-20** [MaikKlein/ash#566]
Vulkan 1.3.204 was released on January 22nd, 2022

not sure how the process of making this support a new version goes but just FYI in case you missed the new release

**Comment by MarijnS95** [comment]
> Vulkan 1.3.204 was released on January 22nd, 2022

The embargo only lifted yesterday, January 25th. Likewise, the required `vk.xml` was only published yesterday.

> but just FYI in case you missed the new release

Just FYI, in case you missed it: a PR is already open just an hour after `vk.xml` was published to `Vulkan-Headers`: https://github.com/MaikKlein/ash/pull/563. It's not entirely complete yet and blocking on a fix to `vk.xml`, but can already be git-referenced in case you absolutely need to use the new functionality in raw form without going through the extensions.

**Comment by MarijnS95** [comment]
Closing this as the tracking "issue" for Vulkan 1.3 is in fact https://github.com/MaikKlein/ash/pull/563.
