### ISSUE TITLE
Some bitflag structures are empty

### ISSUE THREAD

**Issue by psionic12** [MaikKlein/ash#587]
For example, the struct `DeviceQueueCreateFlags` do not have any bit fields, but the doc said that there's a field called `VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT` in it.

I think the reason may be that the enum member sits in `register/feature/require/enum` in vk.xml, not the normal path "register/types/"

**Comment by Ralith** [comment]
https://docs.rs/ash/0.36.0+1.3.206/ash/vk/struct.DeviceQueueCreateFlags.html#associatedconstant.PROTECTED
