### ISSUE TITLE
Loading libMoltenVK.dylib instead of libvulkan.dylib on iOS

### ISSUE THREAD

**Issue by jhvst** [MaikKlein/ash#593]
Hi there,

I saw there is an old commit made here: 594a476fdb7a9fe211a7257f353dbf9807e87786, which renamed the dynamic library load path on iOS to be `libvulkan.dylib` instead of `libMoltenVK.dylib`. However, it seems to cause crashes on iOS if the standard MoltenVK build instructions are followed.

In specific, it seems that building MoltenVK somehow internally assumes that the file is named in this specific way. When any code where ash instance is created using the `load()` function, it searches for `libvulkan.dylib` in the iOS Frameworks folder. The unexpected behaviour is that if this file _does_ exists, an error is produced which says that `libMoltenVK.dylib` does not exist. If copies of the two files are added inside the Frameworks folder, everything works.

I can put sample applications online in a few days and submit a PR if this seems something you want to fix. Alternatively, I could try to find a way to fix the naming scheme and make instructions on how to do so. If you already know how to fix this, maybe reference that in the README?

**Comment by jhvst** [comment]
I was not aware that there could be some other loader program that could be used instead of MoltenVK on iOS. Because of this I was thinking that maybe the assumption could be made, but I see the reasoning why this is not the case now.

Thanks for the prompt reply, I will close this ticket for now.

**Comment by MarijnS95** [comment]
I also wasn't aware that `libMoltenVK` could be loaded through the standard Vulkan loader (does MacOS ship with one at all? I've never physically touched this platform). There is however [`ash-molten`](https://github.com/EmbarkStudios/ash-molten/) which statically links against `libMoltenVK` which might do what you need @jhvst?

**Comment by jhvst** [comment]
In my initial description both `libvulkan.dylib` and `libMoltenVK.dylib` are _the same_ file that is produced by the MoltenVK build process for iOS. I now recognize how you might have misread this, but `libvulkan.dylib` is not a Vulkan loader, it's the MoltenVK library renamed. Since there is no other way currently than MoltenVK to use Vulkan bindings on Mac and iOS, I thought that changing the default on iOS makes sense -- I use MacOS as my development machine and this I control with the ICD files as environment paths. My problem with iOS is that I do not know how to set up similar environment paths (I will look into this eventually, but it's not my priority right now), nor did it even occur to me at the time of opening this ticket that I had setup my Mac a long time ago with the ICD paths. With the iOS in particular being more constrained environment, I was thinking if it would make sense to revert the referenced change for iOS.

`ash-molten` is also something I completely missed, the process seems generalized version of mine. I can see why it does not run into the same problem, because it's not using dynamic linking. I think I might as well move into that crate later on. Thanks for the heads-up and sorry about the fuss!

**Comment by Ralith** [comment]
I don't have personal experience with MacOS either, but I do know it doesn't ship with the loader; applications would have to bundle it themselves.

**Comment by MarijnS95** [comment]
> In my initial description both `libvulkan.dylib` and `libMoltenVK.dylib` are _the same_ file that is produced by the MoltenVK build process for iOS. I now recognize how you might have misread this, but `libvulkan.dylib` is not a Vulkan loader, it's the MoltenVK library renamed.

I have not misread this, I have simply subsumed that - if there exists a MacOS loader - it's probably called something like `libvulkan.dylib` (with `.1` actually) which would be a plausible explanation for 594a476fdb7a9fe211a7257f353dbf9807e87786 to exist. I clearly understood that you renamed it in hopes of tricking `ash` into loading `libMoltenVK` through the "ICD loader" library name (this is possible with some drivers, as long as they expose the `vkGetInstanceProcAddr` symbol).

Do Mac `dylib` files have something similar to `SONAME` that might trip up a load function somewhere, resulting in a search for `libMoltenVK.dylib` at all? Are you sure your replaced `libvulkan.dylib` in the right place, that `ash` really isn't accidentally poking the ICD loader library which subsequently tries to find `libMoltenVK.dylib` through a JSON ICD file?

**Comment by MarijnS95** [comment]
@jhvst All I can think about here is the `Referenced from:` explicitly printing your project name and not the "equally-built" `libvulkan.dylib`. Could this error originate from a `dlopen` call or is it implying dynamic linking in the executable? Does Mac have tools like `readelf` to inspect the dynamic linker section? If listed in there, something else could be forcing your application to link dynamically against `libMoltenVK.dylib`. I don't see how `ash/build.rs` could do that though.
