### ISSUE TITLE
UB in matches on DebugReportObjectTypeEXT

### ISSUE THREAD

**Issue by Ralith** [MaikKlein/ash#67]
This value is represented in Rust as an enum, but vulkan can provide values that ash doesn't expect. Worse, ash does not sanity-check them, leading to UB when matching (for example, in the derived `Debug` implementation).

Current ash defines a continuous range of values from 0 to 28 inclusive. By contrast, my vulkan 1.0.61 header defines these additional values:

```c
typedef enum VkDebugReportObjectTypeEXT {
    // ...
    VK_DEBUG_REPORT_OBJECT_TYPE_DISPLAY_KHR_EXT = 29,
    VK_DEBUG_REPORT_OBJECT_TYPE_DISPLAY_MODE_KHR_EXT = 30,
    VK_DEBUG_REPORT_OBJECT_TYPE_OBJECT_TABLE_NVX_EXT = 31,
    VK_DEBUG_REPORT_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NVX_EXT = 32,
    VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT = 33,
    VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_KHR_EXT = 1000085000,
    VK_DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR_EXT = 1000156000,
    VK_DEBUG_REPORT_OBJECT_TYPE_BEGIN_RANGE_EXT = VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT,
    VK_DEBUG_REPORT_OBJECT_TYPE_END_RANGE_EXT = VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT,
    VK_DEBUG_REPORT_OBJECT_TYPE_RANGE_SIZE_EXT = (VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT - VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT + 1),
    VK_DEBUG_REPORT_OBJECT_TYPE_MAX_ENUM_EXT = 0x7FFFFFFF
} VkDebugReportObjectTypeEXT;
```

Given that ash does not constrain the set of possible extensions enabled at runtime (and indeed doing so would be a severe limitation) I believe an enum is fundamentally inappropriate here, as even the application may not be statically aware of all possible values.

It's probably worth revisiting all other uses of rust enums where the vulkan API instead uses an integer constant to check for similar issues.

**Comment by MaikKlein** [comment]
I think this is already addressed in my new generator branch, I just need to find some time to finish it up.

**Comment by Ralith** [comment]
I'm also observing this in `VkResult` values, which is aggravating as it turns what would otherwise be helpful diagnostic panic output on `Result::unwrap` into an illegal instruction crash.

**Comment by Ralith** [comment]
Practically every error I make (on intel) seems to produce UB in unwrap. I'll see if I can come up with some examples.

**Comment by Ralith** [comment]
Here are some result codes that my 1.1.77.0 header declares which ash does not:
```
    VK_ERROR_OUT_OF_POOL_MEMORY = -1000069000,
    VK_ERROR_INVALID_EXTERNAL_HANDLE = -1000072003,
    VK_ERROR_INVALID_SHADER_NV = -1000012000,
    VK_ERROR_FRAGMENTATION_EXT = -1000161000,
    VK_ERROR_NOT_PERMITTED_EXT = -1000174001,
```
`VK_ERROR_OUT_OF_POOL_MEMORY`, for example, is easily reproduced.

I don't think ash should be defining closed rust enums for values that the Vulkan implementation generates unless the spec makes a very clear guarantee that no new cases will ever be defined.

**Comment by MaikKlein** [comment]
Fixed
