### ISSUE TITLE
Debug object naming requires transmuting

### ISSUE THREAD

**Issue by Ralith** [MaikKlein/ash#70]
`vk::DebugMarkerObjectNameInfoEXT` requires an object handle as a `uint64_t`, but ash's handle wrappers appear to all be opaque, making a transmute necessary to get the value out. To address this, I'd like to implement something like:
```rust
trait Handle {
  const TYPE: DebugReportObjectTypeEXT;
  fn into_raw(self) -> u64;
}
```
However, I hesitate to dive into that with the generator rewrite looming, as I'm not sure what all will be affected.

**Comment by MaikKlein** [comment]
In this case a simple cast is enough, but I am thinking of implementing those enums differently.

**Comment by Ralith** [comment]
What enums?

**Comment by MaikKlein** [comment]
Sorry I didn't read to carefully and I have personally not used the debug marker extension. I assume object here can be any vulkan object?

This is how it is define in the c header 
```
#if !defined(VK_DEFINE_NON_DISPATCHABLE_HANDLE)
#if defined(__LP64__) || defined(_WIN64) || (defined(__x86_64__) && !defined(__ILP32__) ) || defined(_M_X64) || defined(__ia64) || defined (_M_IA64) || defined(__aarch64__) || defined(__powerpc64__)
        #define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef struct object##_T *object;
#else
        #define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef uint64_t object;
#endif
#endif
```

I am actually not sure why it is defined this way. It seems if we are on an x64 system it is a ptr which then has the size of uint64 or it is just an uint64. Ash currently always defines this to an u64.

This sample simply casts the objects to u64  https://github.com/SaschaWillems/Vulkan/blob/master/examples/debugmarker/debugmarker.cpp#L465.

I think we can just expose the inner u64 value. So can you can simply do `some_sampler.handle`.

**Comment by MaikKlein** [comment]
Btw the "opaque" types are defined with this macro https://github.com/MaikKlein/ash/blob/master/ash/src/vk.rs#L13.

**Comment by Ralith** [comment]
> I assume object here can be any vulkan object?

Yes.

> I am actually not sure why it is defined this way. It seems if we are on an x64 system it is a ptr which then has the size of uint64 or it is just an uint64. Ash currently always defines this to an u64.

I believe this is done to improve typechecking in C/C++ applications, where implicit conversions between pointers are more difficult to perform by accident.

> I think we can just expose the inner u64 value. So can you can simply do some_sampler.handle.

Yes, that would serve. I'd like to have the trait for convenience of generic code, and so we can hang other things off it like the type constant. That would allow e.g. `impl DebugReport { fn set_name<T: Handle>(&self, object: T, name: &CStr) { ... } }` to be written.

> Btw the "opaque" types are defined with this macro https://github.com/MaikKlein/ash/blob/master/ash/src/vk.rs#L13.

Is this subject to change in the upcoming refactoring? I'd rather not write/update a bunch of boilerplate that's about to be replaced.
