### ISSUE TITLE
Enums need to be handled differently

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/ash#71]
There are two types of enums`Vk -> Ash` and `Ash -> Vk`. Only the enums that come out of Vulkan are problematic, like `Result`.

The reason for this is that the Vulkan spec is not completely strict and sends out new values, even if the created vulkan version doesn't support them.

So if you create a 1.0 context, you might get values for 1.1. Because those values are represented as enums, they will just crash.

First problematic enum

```
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub enum DebugReportObjectTypeEXT {
        Unknown = 0,
        Instance = 1,
        PhysicalDevice = 2,
        Device = 3,
        Queue = 4,
        Semaphore = 5,
        CommandBuffer = 6,
        Fence = 7,
        DeviceMemory = 8,
        Buffer = 9,
        Image = 10,
        Ent = 11,
        QueryPool = 12,
        BufferView = 13,
        ImageView = 14,
        ShaderModule = 15,
        PipelineCache = 16,
        PipelineLayout = 17,
        RenderPass = 18,
        Pipeline = 19,
        DescriptorSetLayout = 20,
        Sampler = 21,
        DescriptorPool = 22,
        DescriptorSet = 23,
        Framebuffer = 24,
        CommandPool = 25,
        SurfaceKhr = 26,
        SwapchainKhr = 27,
        DebugReport = 28,
    } 
```

Which for example appears directly in a callback

```
    pub type PFN_vkDebugReportCallbackEXT = unsafe extern "system" fn(
        DebugReportFlagsEXT,
        DebugReportObjectTypeEXT,
        uint64_t,
        size_t,
        int32_t,
        *const c_char,
        *const c_char,
        *mut c_void,
    ) -> Bool32;
```

This will just straight up crash, if an unknown value comes in.

This is how it looked in 1.0. https://vulkan.lunarg.com/doc/view/1.0.30.0/linux/vkspec.chunked/ch32s01.html#VkDebugReportObjectTypeEXT

and now 

https://github.com/KhronosGroup/Vulkan-Headers/blob/master/include/vulkan/vulkan_core.h#L5855

A quick search indicates that enum constants in C are of type `i32`, so casting a value that is outside of the range of the enum seems to be allowed in C.

How should this be handled in Ash? Reprenting them as enum will cause a crash.

We could simply typedef to a primitive type.

```
pub type Result = i32`
``` 
We could technically generate custom error types for every function because all possible error codes are included in the vk.xml file

```
Command {
    name: "vkAllocateDescriptorSets",
    ....
    errorcodes: Some(
            "VK_ERROR_OUT_OF_HOST_MEMORY,VK_ERROR_OUT_OF_DEVICE_MEMORY,VK_ERROR_FRAGMENTED_POOL,VK_ERROR_OUT_OF_POOL_MEMORY"
        )
    },
    ....
}
```

So instead of 

```
    unsafe fn allocate_descriptor_sets(
        &self,
        create_info: &vk::DescriptorSetAllocateInfo,
    ) -> VkResult<Vec<vk::DescriptorSet>> {
```

We could have 

```
    unsafe fn allocate_descriptor_sets(
        &self,
        create_info: &vk::DescriptorSetAllocateInfo,
    ) -> Result<Vec<vk::DescriptorSet>, AllocateDescriptorSetsError> {..}

    pub enum AllocateDescriptorSetsError {
            OutOfHostMemory,
            OutOfDeviceMemory,
            ...
     }
```

That would be super ergonomic, but I just know that the Vulkan spec will break this in the future. For example a future version might add more error codes, and then Ash would crash again, so the semantics would need to change to something like 

```
    unsafe fn allocate_descriptor_sets(
        &self,
        create_info: &vk::DescriptorSetAllocateInfo,
    ) -> Result<Vec<vk::DescriptorSet>, Option<AllocateDescriptorSetsError>> {..}
```

Instead of using enums we could simply do

```
pub struct AllocateDescriptorSetsError(pub i32);
impl AllocateDescriptorSetsError {
    pub fn out_of_host_memory(self) -> bool {..}
    ...
}

```

And the same thing can be done to `DebugReportObjectTypeEXT` and every other enum that comes from Vulkan to Ash.

Of course here custom errors per function here is optional. We can still do

```
pub struct Result(pub i32);
impl Result {
    pub fn out_of_device_memory(self) -> bool {..}
    // other cases
}
unsafe fn allocate_descriptor_sets(
    &self,
    create_info: &vk::DescriptorSetAllocateInfo,
) -> Result<Vec<vk::DescriptorSet>, vk::Result> {..}
```

**Comment by Ralith** [comment]
When binding C library error codes, I like to do something like:
```rust
#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub struct Result(i32);
impl From<i32> for Result { ... }
impl From<Result> for i32 { ... }
impl Result {
   pub const OUT_OF_HOST_MEMORY: Self = Result(...);
}
```

This can be used with syntax and typechecking *almost* identical to that of an enum, and you can hang things like `impl fmt::Debug` off it which might even call out to foreign pretty printers, without requiring the full set of values be known in advance.

How confident are we that there is and will always be a clear line between types for which values might be obtained from Vulkan versus ones which will only ever be constructed by an application?

**Comment by MaikKlein** [comment]
@Ralith I didn't even know what we could define constants inside an `impl`, and racer can even complete them. That seems to be the best way to represent enums generally. Of course this will be an annoying breaking change for the current users.  But I  think every enum should be represented this way.

This also greatly simplifies the generator, because extensions can add variants to various enums. But if constants are defined inside an `impl`, I can just add another `impl` for a new extension and I don't have to consider some special cases.
