### ISSUE TITLE
Use [repr(transparent)] instead of [repr(C)]

### ISSUE THREAD

**Issue by Cyres** [MaikKlein/ash#72]
Since [`[repr(transparent)]` is now stabilized](https://github.com/rust-lang/rust/pull/51562) you may consider to use it instead of `[repr(C)]` for the handles ([here](https://github.com/MaikKlein/ash/blob/d49bf7d409c049c75300fb0656e1902825e96829/ash/src/vk.rs#L15) and [here](https://github.com/MaikKlein/ash/blob/d49bf7d409c049c75300fb0656e1902825e96829/ash/src/vk.rs#L40)).

I'd do a PR if you want. This could also be enabled with a feature.

**Comment by MaikKlein** [comment]
We will switch to it when it is on stable.

**Comment by omni-viral** [comment]
It should be stable in 1.28 though.

**Comment by Cyres** [comment]
It's stabilized on 1.28 but the stable branch is 1.26 currently.

**Comment by omni-viral** [comment]
I believe it is 1.27

**Comment by Cyres** [comment]
Oh, right. However, not 1.28 though :)

**Comment by omni-viral** [comment]
It's time.
