### ISSUE TITLE
API constants has wrong type

### ISSUE THREAD

**Issue by Cyres** [MaikKlein/ash#76]
The [API constants](https://github.com/KhronosGroup/Vulkan-Docs/blob/81ce46fe9bcef5e5182f3d4dee2136c7ee50dcfc/src/spec/vk.xml#L5511) have the wrong type: `usize`, while it should be `u32`.

Wrong constants: 
```
pub const VK_MAX_PHYSICAL_DEVICE_NAME_SIZE: usize = 256;
pub const VK_UUID_SIZE: usize = 16;
pub const VK_LUID_SIZE: usize = 8;
pub const VK_MAX_EXTENSION_NAME_SIZE: usize = 256;
pub const VK_MAX_DESCRIPTION_SIZE: usize = 256;
pub const VK_MAX_MEMORY_TYPES: usize = 32;
pub const VK_MAX_MEMORY_HEAPS: usize = 16;
pub const VK_TRUE: usize = 1;
pub const VK_FALSE: usize = 0;
pub const VK_MAX_DEVICE_GROUP_SIZE: usize = 32;
```

While it would be handy to leave them `usize` (e.g. for arrays), it may use the wrong registers when returning them from functions in the API (like debug report callback)

**Comment by MaikKlein** [comment]
> While it would be handy to leave them usize (e.g. for arrays), it may use the wrong registers when returning them from functions in the API (like debug report callback)

Sorry I don't see the problem. Could you provide an example where this would be illegal? They are essentially type less in the vulkan header.

`#define VK_MAX_EXTENSION_NAME_SIZE 256`

And how do you know they are supposed to be u32? Because of the enum tag? Aren't enums with a value of type i32?

**Comment by Ralith** [comment]
> it may use the wrong registers when returning them from functions in the API (like debug report callback)

Any function call that crosses the FFI boundary should have an concrete return type that would make this impossible. For example, the debug report callback returns `Bool32`.
