### ISSUE TITLE
Getting ptr from handle for interacting with other libraries

### ISSUE THREAD

**Issue by LaylConway** [MaikKlein/ash#78]
I'm trying to make use of Vulkan Memory Allocator, which asks me to give it the inner pointers of the Device and PhysicalDevice handles. However with ash's current API I can't seem to access these.

**Comment by MaikKlein** [comment]
Can you show me an example where this is needed?

**Comment by LaylConway** [comment]
Here's an example:
https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/quick_start.html#quick_start_initialization

**Comment by MaikKlein** [comment]
I assume your problem is that you used something like bindgen and now VkDevice/VkInstance are typdefs to a pointer? A transmute to the types should work, or you can just use the ash types in the generated code. Everything should map 1:1.

**Comment by LaylConway** [comment]
Ah, didn't know they could just be transmuted. I did use bindgen yea as that seemed like the best approach to quickly get bindings to the library.
