### ISSUE TITLE
free_command_buffers()

### ISSUE THREAD

**Issue by mikedilger** [MaikKlein/ash#8]
I don't see DeviceV1_0::free_command_buffers()
Is that just an oversight?

**Comment by MaikKlein** [comment]
@mikedilger Yes, there are actually a bunch of missing functions at the moment. You can still use the "raw" C function with `some_device.fp_v1_0().free_command_buffers(..);` as a temporary workaround. I'll add it this week.

I mostly only wrap functions that I currently use in my project and I never free command buffers at all, I only free them by destroying the pool, or I just reset them.

**Comment by MaikKlein** [comment]
Fixed by https://github.com/MaikKlein/ash/commit/463e862a45b56f7a3e2221d6ad62532ddb8ecd21
