### ISSUE TITLE
pp_ - fields expects single pointer

### ISSUE THREAD

**Issue by Cyres** [MaikKlein/ash#82]
`pp_`-fields like [`InstanceCreateInfo::pp_enabled_layer_names`](https://github.com/MaikKlein/ash/blob/f04df1e1dfee4c26ccf7b2b8f9b07bf5840bfaee/ash/src/vk.rs#L5164) expects `*const c_char` but should expect `*const *const c_char`. 

[See the specs](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkInstanceCreateInfo.html):

```C
typedef struct VkInstanceCreateInfo {
    VkStructureType             sType;
    const void*                 pNext;
    VkInstanceCreateFlags       flags;
    const VkApplicationInfo*    pApplicationInfo;
    uint32_t                    enabledLayerCount;
    const char* const*          ppEnabledLayerNames;
    uint32_t                    enabledExtensionCount;
    const char* const*          ppEnabledExtensionNames;
} VkInstanceCreateInfo;
```

**Comment by MaikKlein** [comment]
Should be addressed in https://github.com/MaikKlein/ash/commit/56bf57acf5b7a58442f6ad734d8f75b9535a0694
