### ISSUE TITLE
Remove _EXT and _KHR from extension enums

### ISSUE THREAD

**Issue by Cyres** [MaikKlein/ash#84]
Currently, we have `DebugReportFlagsEXT::ERROR_EXT`, `_EXT` is redundant here.

**Comment by MaikKlein** [comment]
I don't think it is possible, extensions can extend extensions and I at least run into one issue where removing the vendor extension name resulted in an unambiguous name. I'll have a look at it later if at least some vendor extensions can be removed.

**Comment by MaikKlein** [comment]
Fixed in 666e5628ac9cf37084d0a5f9bc5eb5dd6c41c72c
