### ISSUE TITLE
Segfault in the new generator branch in a release build

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/ash#89]
The examples in the generator branch now segfault on my machine if they are built with the `release` flag.

```
➜  examples git:(racer) cargo run --bin triangle --release
    Finished release [optimized] target(s) in 0.07s
     Running `/home/maik/projects/ash/target/release/triangle`
fish: “cargo run --bin triangle --rele…” terminated by signal SIGILL (Illegal instruction)
```

Can anyone reproduce this?

**Comment by MaikKlein** [comment]
Okay I tracked the issue down to two things. It only segfaults with the current nightly and it seems to be related to winit. Also the winit version in the examples is a few version behind, it might be worth updating.

**Comment by MaikKlein** [comment]
I just updated the examples to `0.16` but it still segaults. I tried to run some winit examples and they all segfault for me too, so it doesn't seem to be related to ash.

**Comment by GabrielMajeri** [comment]
Probably caused by erlepereira/x11-rs#90. That lib is triggering undefined behavior which causes an illegal instruction to be generated. And unfortunately fixing this is... complicated: erlepereira/x11-rs#91, rust-lang/rust#52960
