### ISSUE TITLE
All functions that use any kind of handle should be marked unsafe

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/ash#94]
For example every handle can be a null handle, and therefore all functions that use those handles should be marked `unsafe`. 

Should those handles be allowed to be created by the user, or only the API itself? If they are not allowed to be created by the user, then more functions should be allowed to be safe. But the default trait can not be implemented on handles.

I honestly think we should just mark everything as `unsafe`, so that we don't accidentally break the safety guarantees of Rust.

Any thoughts?

**Comment by Ralith** [comment]
> For example every handle can be a null handle, and therefore all functions that use those handles should be marked unsafe.

Many vulkan functions are just fine with receiving a null handle. For example, `vkQueueSubmit` is often passed a null fence.

It might be interesting to explore defining handles as newtypes of `NonZeroU64` and using `Option` as appropriate, but I imagine it would be very labor-intensive to apply across the board.

> Should those handles be allowed to be created by the user, or only the API itself?

Interoperation with external libs requires that either the lib uses ash's handle types (unlikely) or the user be able to freely convert handles to/from `u64`.

**Comment by Cyres** [comment]
> It might be interesting to explore defining handles as newtypes of `NonZeroU64` and using `Option` as appropriate

I really like the Idea.

> I imagine it would be very labor-intensive to apply across the board.

This can be automated. See `vkQueueSubmit` in `vk.xml`:

```xml
<command successcodes="VK_SUCCESS" errorcodes="VK_ERROR_OUT_OF_HOST_MEMORY,VK_ERROR_OUT_OF_DEVICE_MEMORY,VK_ERROR_DEVICE_LOST">
    <proto><type>VkResult</type> <name>vkQueueSubmit</name></proto>
    <param externsync="true"><type>VkQueue</type> <name>queue</name></param>
    <param optional="true"><type>uint32_t</type> <name>submitCount</name></param>
    <param len="submitCount" externsync="pSubmits[].pWaitSemaphores[],pSubmits[].pSignalSemaphores[]">const <type>VkSubmitInfo</type>* <name>pSubmits</name></param>
    <param optional="true" externsync="true"><type>VkFence</type> <name>fence</name></param>
</command>
```

The `fence` parameter is marked as Optional.

**Comment by Ralith** [comment]
Oooh. If those annotations are accurate and comprehensive, then this could work. Does anyone know if the ABI of `Option<NonZeroU64>` is well defined?

**Comment by Cyres** [comment]
Yup, it is: https://blog.rust-lang.org/2018/08/02/Rust-1.28.html#library-stabilizations

**Comment by Ralith** [comment]
Although to address the original question, I think functions that process handles should still be unsafe across the board because many more interesting dynamic legality restrictions apply, such as "this handle was not freed," or "this handle is not being concurrently used by another thread," or ...

**Comment by Cyres** [comment]
@Ralith you may open another issue for the `NonZeroU64` thing?

**Comment by Ralith** [comment]
See #95
